import { FAMILY_LABEL } from "@/lib/facets";
import type { Work } from "@/lib/work";

export type WorkFacts = {
  director?: string;
  cast?: string;
  genre?: string;
  google?: string;
  imdb?: string;
  rotten?: string;
};

export const FACTS: Record<string, WorkFacts> = {
  "a-prophet": { director: "Jacques Audiard", cast: "Tahar Rahim, Niels Arestrup, Adel Bencherif", genre: "Crime, Drama", imdb: "7.8", rotten: "96%" },
  "a-separation": { director: "Asghar Farhadi", cast: "Payman Maadi, Leila Hatami, Sareh Bayat", genre: "Drama", imdb: "8.3", rotten: "99%" },
  "aftersun": { director: "Charlotte Wells", cast: "Paul Mescal, Frankie Corio, Celia Rowlson-Hall", genre: "Drama", imdb: "7.6", rotten: "96%" },
  "age-of-innocence": { director: "Martin Scorsese", cast: "Daniel Day-Lewis, Michelle Pfeiffer, Winona Ryder", genre: "Drama, Romance", imdb: "7.2", rotten: "87%" },
  "all-quiet": { director: "Edward Berger", cast: "Felix Kammerer, Albrecht Schuch, Aaron Hilmer", genre: "Drama, History", imdb: "7.8", rotten: "90%" },
  "amadeus": { director: "Milos Forman", cast: "F. Murray Abraham, Tom Hulce, Elizabeth Berridge", genre: "Biography, Drama", imdb: "8.4", rotten: "90%" },
  "american-beauty": { director: "Sam Mendes", cast: "Kevin Spacey, Annette Bening, Thora Birch", genre: "Drama", imdb: "8.3", rotten: "87%" },
  "american-pie": { director: "Paul Weitz", cast: "Jason Biggs, Chris Klein, Thomas Ian Nicholas", genre: "Comedy", imdb: "7.0", rotten: "62%" },
  "anatomy-of-a-fall": { director: "Justine Triet", cast: "Sandra Hüller, Swann Arlaud, Milo Machado-Graner", genre: "Crime, Drama", imdb: "7.6", rotten: "96%" },
  "andor": { director: "Toby Haynes, Susanna White, Benjamin Caron", cast: "Diego Luna, Denise Gough, Stellan Skarsgård", genre: "Adventure, Drama", imdb: "8.6", rotten: "96%" },
  "another-round": { director: "Thomas Vinterberg", cast: "Mads Mikkelsen, Thomas Bo Larsen, Magnus Millang", genre: "Comedy, Drama", imdb: "7.7", rotten: "92%" },
  "army-of-shadows": { director: "Jean-Pierre Melville", cast: "Lino Ventura, Paul Meurisse, Jean-Pierre Cassel", genre: "Drama, War", imdb: "8.1", rotten: "97%" },
  "arrival": { director: "Denis Villeneuve", cast: "Amy Adams, Jeremy Renner, Forest Whitaker", genre: "Drama, Mystery", imdb: "7.9", rotten: "94%" },
  "babadook": { director: "Jennifer Kent", cast: "Essie Davis, Noah Wiseman, Daniel Henshall", genre: "Drama, Horror", imdb: "6.8", rotten: "98%" },
  "band-of-brothers": { cast: "Scott Grimes, Damian Lewis, Ron Livingston", genre: "Action, Drama", imdb: "9.4", rotten: "94%" },
  "barry-lyndon": { director: "Stanley Kubrick", cast: "Ryan O'Neal, Marisa Berenson, Patrick Magee", genre: "Adventure, Drama", imdb: "8.1", rotten: "78%" },
  "batman-nolan": { director: "Christopher Nolan", cast: "Christian Bale, Michael Caine, Gary Oldman, Morgan Freeman", genre: "Action, Crime" },
  "black-bird": { director: "Michaël R. Roskam", cast: "Taron Egerton, Paul Walter Hauser, Greg Kinnear", genre: "Biography, Crime", imdb: "8.1", rotten: "98%" },
  "black-swan": { director: "Darren Aronofsky", cast: "Natalie Portman, Mila Kunis, Vincent Cassel", genre: "Drama, Thriller", imdb: "8.0", rotten: "85%" },
  "boardwalk": { director: "Martin Scorsese, Tim Van Patten", cast: "Steve Buscemi, Kelly Macdonald, Michael Shannon", genre: "Crime, Drama", imdb: "8.6", rotten: "92%" },
  "bone-collector": { director: "Phillip Noyce", cast: "Denzel Washington, Angelina Jolie, Queen Latifah", genre: "Crime, Drama", imdb: "6.7", rotten: "29%" },
  "breaking-bad": { cast: "Bryan Cranston, Aaron Paul, Anna Gunn", genre: "Crime, Drama", imdb: "9.5", rotten: "96%" },
  "bronx-tale": { director: "Robert De Niro", cast: "Robert De Niro, Chazz Palminteri, Lillo Brancato", genre: "Crime, Drama", imdb: "7.8", rotten: "97%" },
  "bullitt": { director: "Peter Yates", cast: "Steve McQueen, Jacqueline Bisset, Robert Vaughn", genre: "Action, Crime", imdb: "7.4", rotten: "98%" },
  "call-me": { director: "Luca Guadagnino", cast: "Timothée Chalamet, Armie Hammer, Michael Stuhlbarg", genre: "Drama, Romance", imdb: "7.8", rotten: "94%" },
  "casino": { director: "Martin Scorsese", cast: "Robert De Niro, Sharon Stone, Joe Pesci", genre: "Crime, Drama", imdb: "8.2", rotten: "79%" },
  "casino-royale": { director: "Martin Campbell", cast: "Daniel Craig, Eva Green, Judi Dench", genre: "Action, Adventure", imdb: "8.0", rotten: "94%" },
  "chernobyl": { director: "Johan Renck", cast: "Jared Harris, Jessie Buckley, Stellan Skarsgård", genre: "Drama, History", imdb: "9.3", rotten: "95%" },
  "civil-war": { director: "Alex Garland", cast: "Kirsten Dunst, Wagner Moura, Cailee Spaeny", genre: "Action, Thriller", imdb: "7.0", rotten: "81%" },
  "come-and-see": { director: "Elem Klimov", cast: "Aleksey Kravchenko, Olga Mironova, Liubomiras Laucevicius", genre: "Drama, Thriller", imdb: "8.3", rotten: "90%" },
  "counterpart": { director: "Stephen Williams, Morten Tyldum, Alik Sakharov", cast: "J.K. Simmons, Olivia Williams, Harry Lloyd", genre: "Drama, Sci-Fi", imdb: "8.0", rotten: "100%" },
  "crazy-stupid-love": { director: "Glenn Ficarra, John Requa", cast: "Steve Carell, Ryan Gosling, Julianne Moore", genre: "Comedy, Drama", imdb: "7.4", rotten: "79%" },
  "dark": { director: "Baran bo Odar", cast: "Louis Hofmann, Karoline Eichhorn, Lisa Vicari", genre: "Crime, Drama", imdb: "8.7", rotten: "95%" },
  "dead-poets": { director: "Peter Weir", cast: "Robin Williams, Robert Sean Leonard, Ethan Hawke", genre: "Comedy, Drama", imdb: "8.1", rotten: "84%" },
  "death-of-stalin": { director: "Armando Iannucci", cast: "Steve Buscemi, Simon Russell Beale, Jeffrey Tambor", genre: "Comedy, Drama", imdb: "7.3", rotten: "95%" },
  "defending-jacob": { director: "Morten Tyldum", cast: "Chris Evans, Michelle Dockery, Jaeden Martell", genre: "Crime, Drama", imdb: "7.8", rotten: "70%" },
  "deutschland-83": { director: "Edward Berger", cast: "Jonas Nay, Maria Schrader, Ulrich Noethen", genre: "Drama, Romance", imdb: "8.0", rotten: "91%" },
  "devs": { director: "Alex Garland", cast: "Sonoya Mizuno, Nick Offerman, Jin Ha", genre: "Drama, Mystery", imdb: "7.6", rotten: "82%" },
  "donnie-brasco": { director: "Mike Newell", cast: "Al Pacino, Johnny Depp, Michael Madsen", genre: "Biography, Crime", imdb: "7.7", rotten: "88%" },
  "donnie-darko": { director: "Richard Kelly", cast: "Jake Gyllenhaal, Jena Malone, Mary McDonnell", genre: "Drama, Mystery", imdb: "8.0", rotten: "87%" },
  "drops-of-god": { director: "Oded Ruskin", cast: "Fleur Geffrier, Tomohisa Yamashita, Tom Wozniczka", genre: "Drama", imdb: "8.0", rotten: "96%" },
  "dunkirk": { director: "Christopher Nolan", cast: "Fionn Whitehead, Barry Keoghan, Mark Rylance", genre: "Action, Drama", imdb: "7.8", rotten: "92%" },
  "entourage": { cast: "Kevin Connolly, Adrian Grenier, Kevin Dillon", genre: "Comedy, Drama", imdb: "8.4", rotten: "66%" },
  "fargo": { cast: "Billy Bob Thornton, Martin Freeman, Allison Tolman", genre: "Crime, Drama" },
  "festen": { director: "Thomas Vinterberg", cast: "Ulrich Thomsen, Henning Moritzen, Thomas Bo Larsen", genre: "Drama", imdb: "8.0", rotten: "91%" },
  "fight-club": { director: "David Fincher", cast: "Brad Pitt, Edward Norton, Meat Loaf", genre: "Crime, Drama", imdb: "8.8", rotten: "81%" },
  "first-reformed": { director: "Paul Schrader", cast: "Ethan Hawke, Amanda Seyfried, Cedric The Entertainer", genre: "Drama, Mystery", imdb: "7.1", rotten: "93%" },
  "force-majeure": { director: "Ruben Östlund", cast: "Johannes Kuhnke, Lisa Loven Kongsli, Clara Wettergren", genre: "Comedy, Drama", imdb: "7.2", rotten: "94%" },
  "fringe": { director: "J. J. Abrams", cast: "Anna Torv, Joshua Jackson, John Noble", genre: "Drama, Mystery", imdb: "8.4", rotten: "91%" },
  "from": { cast: "Harold Perrineau, Catalina Sandino Moreno, David Alpay", genre: "Drama, Horror", imdb: "7.8", rotten: "96%" },
  "gangs-of-new-york": { director: "Martin Scorsese", cast: "Leonardo DiCaprio, Cameron Diaz, Daniel Day-Lewis", genre: "Crime, Drama", imdb: "7.5", rotten: "72%" },
  "godfather": { director: "Francis Ford Coppola", cast: "Marlon Brando, Al Pacino, James Caan", genre: "Crime, Drama", imdb: "9.2", rotten: "97%" },
  "goldfinger": { director: "Guy Hamilton", cast: "Sean Connery, Gert Fröbe, Honor Blackman", genre: "Action, Adventure", imdb: "7.7", rotten: "99%" },
  "gomorrah": { director: "Francesca Comencini, Stefano Sollima", cast: "Salvatore Esposito, Marco D'Amore, Cristiana Dell'Anna", genre: "Crime, Drama", imdb: "8.6", rotten: "85%" },
  "gone-with-the-wind": { director: "Victor Fleming", cast: "Clark Gable, Vivien Leigh, Thomas Mitchell", genre: "Drama, Romance", imdb: "8.2", rotten: "90%" },
  "goodfellas": { director: "Martin Scorsese", cast: "Robert De Niro, Ray Liotta, Joe Pesci", genre: "Biography, Crime", imdb: "8.7", rotten: "93%" },
  "gotti": { director: "Robert Harmon", cast: "Armand Assante, Anthony Quinn, William Forsythe", genre: "Biography, Crime", imdb: "7.2", rotten: "60%" },
  "hamnet": { director: "Chloé Zhao", cast: "Jessie Buckley, Paul Mescal, Zac Wishart", genre: "Biography, Drama", imdb: "7.8", rotten: "86%" },
  "hannibal": { cast: "Hugh Dancy, Mads Mikkelsen, Caroline Dhavernas", genre: "Crime, Drama", imdb: "8.5", rotten: "93%" },
  "harry-potter": { director: "Chris Columbus, Alfonso Cuarón, Mike Newell, David Yates", cast: "Daniel Radcliffe, Rupert Grint, Emma Watson", genre: "Adventure, Family" },
  "heat": { director: "Michael Mann", cast: "Al Pacino, Robert De Niro, Val Kilmer", genre: "Action, Crime", imdb: "8.3", rotten: "84%" },
  "hereditary": { director: "Ari Aster", cast: "Toni Collette, Milly Shapiro, Gabriel Byrne", genre: "Drama, Horror", imdb: "7.3", rotten: "90%" },
  "his-house": { director: "Remi Weekes", cast: "Sope Dirisu, Wunmi Mosaku, Malaika Wakoli-Abigaba", genre: "Drama, Horror", imdb: "6.4", rotten: "100%" },
  "in-bruges": { director: "Martin McDonagh", cast: "Colin Farrell, Brendan Gleeson, Ciarán Hinds", genre: "Comedy, Crime", imdb: "7.9", rotten: "84%" },
  "in-the-loop": { director: "Armando Iannucci", cast: "Tom Hollander, Peter Capaldi, James Gandolfini", genre: "Comedy", imdb: "7.4", rotten: "94%" },
  "inception": { director: "Christopher Nolan", cast: "Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page", genre: "Action, Adventure", imdb: "8.8", rotten: "87%" },
  "innocents-2021": { director: "Eskil Vogt", cast: "Rakel Lenora Petersen Fløttum, Alva Brynsmo Ramstad, Sam Ashraf", genre: "Drama, Fantasy", imdb: "7.0", rotten: "96%" },
  "interstellar": { director: "Christopher Nolan", cast: "Matthew McConaughey, Anne Hathaway, Jessica Chastain", genre: "Adventure, Drama", imdb: "8.7", rotten: "73%" },
  "irishman": { director: "Martin Scorsese", cast: "Robert De Niro, Al Pacino, Joe Pesci", genre: "Biography, Crime", imdb: "7.8", rotten: "95%" },
  "it-follows": { director: "David Robert Mitchell", cast: "Maika Monroe, Keir Gilchrist, Olivia Luccardi", genre: "Horror, Mystery", imdb: "6.8", rotten: "95%" },
  "la-piscine": { director: "Jacques Deray", cast: "Alain Delon, Romy Schneider, Maurice Ronet", genre: "Crime, Drama", imdb: "7.1", rotten: "95%" },
  "lamb": { director: "Valdimar Jóhannsson", cast: "Noomi Rapace, Hilmir Snær Guðnason, Björn Hlynur Haraldsson", genre: "Drama, Fantasy", imdb: "6.3", rotten: "86%" },
  "let-the-right-one-in": { director: "Tomas Alfredson", cast: "Kåre Hedebrant, Lina Leandersson, Per Ragnar", genre: "Drama, Fantasy", imdb: "7.8", rotten: "98%" },
  "leviathan": { director: "Andrey Zvyagintsev", cast: "Aleksey Serebryakov, Elena Lyadova, Roman Madyanov", genre: "Crime, Drama", imdb: "7.6", rotten: "97%" },
  "lighthouse": { director: "Robert Eggers", cast: "Robert Pattinson, Willem Dafoe, Valeriia Karaman", genre: "Drama, Fantasy", imdb: "7.4", rotten: "90%" },
  "live-and-let-die": { director: "Guy Hamilton", cast: "Roger Moore, Yaphet Kotto, Jane Seymour", genre: "Action, Adventure", imdb: "6.7", rotten: "67%" },
  "lives-of-others": { director: "Florian Henckel von Donnersmarck", cast: "Ulrich Mühe, Martina Gedeck, Sebastian Koch", genre: "Drama, Mystery", imdb: "8.4", rotten: "92%" },
  "lotr": { director: "Peter Jackson", cast: "Elijah Wood, Ian McKellen, Viggo Mortensen, Sean Astin", genre: "Adventure, Drama" },
  "loveless": { director: "Andrey Zvyagintsev", cast: "Maryana Spivak, Aleksey Rozin, Matvey Novikov", genre: "Drama", imdb: "7.6", rotten: "94%" },
  "mad-men": { cast: "Jon Hamm, Elisabeth Moss, Vincent Kartheiser", genre: "Drama", imdb: "8.7", rotten: "94%" },
  "manchester": { director: "Kenneth Lonergan", cast: "Casey Affleck, Michelle Williams, Kyle Chandler", genre: "Drama", imdb: "7.8", rotten: "96%" },
  "marty-supreme": { director: "Josh Safdie", cast: "Timothée Chalamet, Gwyneth Paltrow, Odessa A&apos;zion", genre: "Drama, Sport", imdb: "7.7", rotten: "94%" },
  "medici": { director: "Sergio Mimica-Gezzan", cast: "Daniel Sharman, Alessandra Mastronardi, Synnove Karlsen", genre: "Biography, Drama", imdb: "7.8" },
  "millers-crossing": { director: "Joel Coen, Ethan Coen", cast: "Gabriel Byrne, Albert Finney, John Turturro", genre: "Crime, Drama", imdb: "7.7", rotten: "93%" },
  "mindhunter": { director: "David Fincher", cast: "Jonathan Groff, Holt McCallany, Anna Torv", genre: "Crime, Drama", imdb: "8.6", rotten: "97%" },
  "munich": { director: "Steven Spielberg", cast: "Eric Bana, Daniel Craig, Marie-Josée Croze", genre: "Drama, History", imdb: "7.5", rotten: "78%" },
  "no-time-to-die": { director: "Cary Joji Fukunaga", cast: "Daniel Craig, Ana de Armas, Rami Malek", genre: "Action, Adventure", imdb: "7.3", rotten: "83%" },
  "november": { director: "Rainer Sarnet", cast: "Rea Lest, Jörgen Liik, Arvo Kukumägi", genre: "Drama, Fantasy", imdb: "7.1", rotten: "93%" },
  "oceans": { director: "Steven Soderbergh", cast: "George Clooney, Brad Pitt, Julia Roberts", genre: "Crime, Thriller", imdb: "7.7", rotten: "83%" },
  "once-upon-america": { director: "Sergio Leone", cast: "Robert De Niro, James Woods, Elizabeth McGovern", genre: "Crime, Drama", imdb: "8.3", rotten: "86%" },
  "oppenheimer": { director: "Christopher Nolan", cast: "Cillian Murphy, Emily Blunt, Matt Damon", genre: "Biography, Drama", imdb: "8.2", rotten: "93%" },
  "passion": { director: "Mel Gibson", cast: "Jim Caviezel, Monica Bellucci, Maia Morgenstern", genre: "Drama", imdb: "7.3", rotten: "49%" },
  "prestige": { director: "Christopher Nolan", cast: "Christian Bale, Hugh Jackman, Scarlett Johansson", genre: "Drama, Mystery", imdb: "8.5", rotten: "77%" },
  "presumed-innocent": { director: "Greg Yaitanes, Anne Sewitsky", cast: "Jake Gyllenhaal, Ruth Negga, Bill Camp", genre: "Crime, Drama", imdb: "7.7", rotten: "79%" },
  "prisoners": { director: "Denis Villeneuve", cast: "Hugh Jackman, Jake Gyllenhaal, Viola Davis", genre: "Crime, Drama", imdb: "8.2", rotten: "81%" },
  "promised-land": { director: "Nikolaj Arcel", cast: "Mads Mikkelsen, Amanda Collin, Simon Bennebjerg", genre: "Action, Biography", imdb: "7.7", rotten: "97%" },
  "raging-bull": { director: "Martin Scorsese", cast: "Robert De Niro, Cathy Moriarty, Joe Pesci", genre: "Biography, Drama", imdb: "8.1", rotten: "92%" },
  "return-2003": { director: "Andrey Zvyagintsev", cast: "Vladimir Garin, Ivan Dobronravov, Konstantin Lavronenko", genre: "Drama", imdb: "7.9", rotten: "95%" },
  "ripley-note": { director: "René Clément", cast: "Alain Delon, Maurice Ronet, Marie Laforêt", genre: "Crime, Drama", imdb: "7.7", rotten: "95%" },
  "rome": { director: "Michael Apted, Tim Van Patten", cast: "Kevin McKidd, Ray Stevenson, Polly Walker", genre: "Action, Drama", imdb: "8.7", rotten: "86%" },
  "ronin": { director: "John Frankenheimer", cast: "Robert De Niro, Jean Reno, Natascha McElhone", genre: "Action, Crime", imdb: "7.2", rotten: "70%" },
  "saint-maud": { director: "Rose Glass", cast: "Morfydd Clark, Caoilfhionn Dunne, Jennifer Ehle", genre: "Drama, Horror", imdb: "6.6", rotten: "92%" },
  "servant": { cast: "Lauren Ambrose, Toby Kebbell, Nell Tiger Free", genre: "Drama, Horror", imdb: "7.4", rotten: "90%" },
  "severance": { director: "Ben Stiller, Aoife McArdle", cast: "Adam Scott, Britt Lower, Zach Cherry", genre: "Drama, Mystery", imdb: "8.6", rotten: "95%" },
  "shogun": { cast: "Cosmo Jarvis, Hiroyuki Sanada, Anna Sawai", genre: "Action, Adventure", imdb: "8.6", rotten: "99%" },
  "silence": { director: "Martin Scorsese", cast: "Andrew Garfield, Adam Driver, Liam Neeson", genre: "Drama, History", imdb: "7.2", rotten: "83%" },
  "silo": { director: "Morten Tyldum", cast: "Rebecca Ferguson, Common, Chinaza Uche", genre: "Drama, Mystery", imdb: "8.1", rotten: "92%" },
  "skyfall": { director: "Sam Mendes", cast: "Daniel Craig, Javier Bardem, Naomie Harris", genre: "Action, Adventure", imdb: "7.8", rotten: "92%" },
  "social-network": { director: "David Fincher", cast: "Jesse Eisenberg, Andrew Garfield, Justin Timberlake", genre: "Biography, Drama", imdb: "7.8", rotten: "96%" },
  "sopranos": { director: "Tim Van Patten", cast: "James Gandolfini, Lorraine Bracco, Edie Falco", genre: "Crime, Drama", imdb: "9.2", rotten: "92%" },
  "spectre": { director: "Sam Mendes", cast: "Daniel Craig, Christoph Waltz, Léa Seydoux", genre: "Action, Adventure", imdb: "6.8", rotten: "63%" },
  "superbad": { director: "Greg Mottola", cast: "Michael Cera, Jonah Hill, Christopher Mintz-Plasse", genre: "Comedy", imdb: "7.6", rotten: "88%" },
  "taste-of-things": { director: "Anh Hung Tran", cast: "Juliette Binoche, Benoît Magimel, Emmanuel Salinger", genre: "Drama, History", imdb: "7.4", rotten: "97%" },
  "the-americans": { cast: "Keri Russell, Matthew Rhys, Keidrich Sellati", genre: "Crime, Drama", imdb: "8.4", rotten: "96%" },
  "the-bridge": { cast: "Sofia Helin, Rafael Pettersson, Candice van Litsenborgh", genre: "Crime, Mystery", imdb: "8.6" },
  "the-bureau": { director: "Éric Rochant", cast: "Mathieu Kassovitz, Florence Loiret Caille, Jonathan Zaccaï", genre: "Drama, Thriller", imdb: "8.7" },
  "the-departed": { director: "Martin Scorsese", cast: "Leonardo DiCaprio, Matt Damon, Jack Nicholson", genre: "Crime, Drama", imdb: "8.5", rotten: "91%" },
  "the-hunt": { director: "Thomas Vinterberg", cast: "Mads Mikkelsen, Thomas Bo Larsen, Annika Wedderkopp", genre: "Drama", imdb: "8.3", rotten: "92%" },
  "the-killing": { cast: "Sofie Gråbøl, Morten Suurballe, Lars Mikkelsen", genre: "Crime, Drama", imdb: "8.4" },
  "the-leftovers": { director: "Mimi Leder", cast: "Justin Theroux, Amy Brenneman, Christopher Eccleston", genre: "Drama, Fantasy", imdb: "8.3", rotten: "91%" },
  "the-orphanage": { director: "J.A. Bayona", cast: "Belén Rueda, Fernando Cayo, Roger Príncep", genre: "Drama, Horror", imdb: "7.4", rotten: "87%" },
  "the-returned": { cast: "Anne Consigny, Clotilde Hesme, Frédéric Pierrot", genre: "Drama, Fantasy", imdb: "8.0", rotten: "97%" },
  "the-wire": { cast: "Dominic West, Lance Reddick, Sonja Sohn", genre: "Crime, Drama", imdb: "9.3", rotten: "94%" },
  "the-witch": { director: "Robert Eggers", cast: "Anya Taylor-Joy, Ralph Ineson, Kate Dickie", genre: "Drama, Fantasy", imdb: "7.0", rotten: "91%" },
  "thin-red-line": { director: "Terrence Malick", cast: "Jim Caviezel, Sean Penn, Nick Nolte", genre: "Drama, History", imdb: "7.6", rotten: "80%" },
  "thomas-crown": { director: "Norman Jewison", cast: "Steve McQueen, Faye Dunaway, Paul Burke", genre: "Crime, Drama", imdb: "6.9", rotten: "72%" },
  "tinker-tailor": { director: "Tomas Alfredson", cast: "Gary Oldman, Colin Firth, Tom Hardy", genre: "Drama, Mystery", imdb: "7.0", rotten: "84%" },
  "tomorrow-never-dies": { director: "Roger Spottiswoode", cast: "Pierce Brosnan, Jonathan Pryce, Michelle Yeoh", genre: "Action, Adventure", imdb: "6.5", rotten: "58%" },
  "true-detective": { director: "Cary Joji Fukunaga", cast: "Matthew McConaughey, Woody Harrelson, Michelle Monaghan", genre: "Crime, Drama" },
  "tudors": { cast: "Jonathan Rhys Meyers, Henry Cavill, James Frain", genre: "Drama, History", imdb: "8.1", rotten: "69%" },
  "twin-peaks-return": { director: "David Lynch", cast: "Kyle MacLachlan, Sheryl Lee, Michael Horse", genre: "Crime, Drama", imdb: "8.5", rotten: "94%" },
  "vicky-cristina": { director: "Woody Allen", cast: "Rebecca Hall, Scarlett Johansson, Javier Bardem", genre: "Comedy, Drama", imdb: "7.1", rotten: "80%" },
  "warfare": { director: "Alex Garland, Ray Mendoza", cast: "D'Pharaoh Woon-A-Tai, Will Poulter, Cosmo Jarvis", genre: "Action, Drama", imdb: "7.1", rotten: "92%" },
  "whiplash": { director: "Damien Chazelle", cast: "Miles Teller, J.K. Simmons, Melissa Benoist", genre: "Drama, Music", imdb: "8.5", rotten: "94%" },
  "widows-bay": { cast: "Matthew Rhys, Kate O&apos;Flynn, Kevin Carroll", genre: "Comedy, Drama", imdb: "8.2", rotten: "98%" },
  "wild-tales": { director: "Damián Szifron", cast: "Darío Grandinetti, María Marull, Mónica Villa", genre: "Comedy, Drama", imdb: "8.1", rotten: "94%" },
  "wolf-hall": { director: "Peter Kosminsky", cast: "Mark Rylance, Damian Lewis, Thomas Brodie-Sangster", genre: "Biography, Drama", imdb: "8.2", rotten: "99%" },
  "you-are-not-my-mother": { director: "Kate Dolan", cast: "Hazel Doupe, Carolyn Bracken, Ingrid Craigie", genre: "Drama, Horror", imdb: "5.8", rotten: "89%" },
  "you-wont-be-alone": { director: "Goran Stolevski", cast: "Sara Klimoska, Leontina Bainovic, Anamaria Marinca", genre: "Drama, Fantasy", imdb: "6.4", rotten: "93%" },
  "zodiac": { director: "David Fincher", cast: "Jake Gyllenhaal, Robert Downey Jr., Mark Ruffalo", genre: "Crime, Drama", imdb: "7.7", rotten: "90%" },
};

export function factsFor(work: Pick<Work, "id" | "family">): Required<WorkFacts> {
  const row = FACTS[work.id] ?? {};
  return {
    director: row.director ?? "",
    cast: row.cast ?? "",
    genre: row.genre || FAMILY_LABEL[work.family],
    google: row.google ?? "",
    imdb: row.imdb ?? "",
    rotten: row.rotten ?? "",
  };
}
