import { work, type Work } from "@/lib/work";

export const LOVED: Work[] = [
  work({
    id: "wild-tales",
    name: "Wild Tales",
    year: "2014",
    runtime: "2h 2m",
    loved: true,
    family: "satire",
    vibes: ["heat", "rewatch"],
    facets: { satire: 0.95, moral: 0.75, crime: 0.35, talk: 0.4 },
    summary:
      "Six Argentine stories about ordinary people who decide the slight was enough. Each one starts civil and ends in wreckage.",
    why: "Your satire is not cute. Death of Stalin, Another Round, and this — manners fail, and nobody is let off.",
    vibeLine: "A sharp night. Laugh, then feel the bruise.",
  }),
  work({
    id: "leviathan",
    name: "Leviathan",
    year: "2014",
    runtime: "2h 20m",
    loved: true,
    family: "faith",
    vibes: ["dusk", "folk"],
    seasons: ["autumn", "winter"],
    facets: { faith: 0.7, moral: 0.9, grief: 0.65, folk: 0.35, talk: 0.55 },
    summary:
      "On the Barents coast a man fights the mayor for his house, and the state, the church, and the vodka close in together.",
    why: "Austere, political, and religious without a sermon. Sits with The Hunt and The Passion as judgment, not inspiration.",
    vibeLine: "Cold coast. Faith as weather, not a lesson.",
  }),
  work({
    id: "you-wont-be-alone",
    name: "You Won't Be Alone",
    year: "2022",
    runtime: "1h 48m",
    loved: true,
    family: "folk",
    vibes: ["folk"],
    seasons: ["autumn"],
    facets: { folk: 0.95, grief: 0.7, faith: 0.4, weird: 0.55, moral: 0.45 },
    summary:
      "A girl taken by a witch in 19th-century Macedonia learns how to wear other people's lives. Quiet, bodily, and strange.",
    why: "This is the Lamb cluster at its most literal: folk ritual, a stolen body, tenderness that never turns into a speech.",
    vibeLine: "October folk. Soft voice, hard magic.",
  }),
  work({
    id: "gotti",
    name: "Gotti",
    year: "1996",
    runtime: "1h 56m",
    loved: true,
    weight: 0.7,
    family: "crime",
    vibes: ["heat"],
    facets: { crime: 0.9, moral: 0.45, talk: 0.5, cool: 0.35 },
    summary:
      "Armand Assante as John Gotti, from the Bergin Hunt & Fish Club to the courtroom. The 1996 film, not the later one.",
    why: "A straight mob portrait on the Goodfellas shelf — appetite and law, without Scorsese's music doing the moral work.",
    vibeLine: "Heat. Suits, tapes, and a man who likes being seen.",
  }),
  work({
    id: "marty-supreme",
    name: "Marty Supreme",
    year: "2025",
    runtime: "2h 30m",
    loved: true,
    family: "obsession",
    vibes: ["heat", "rewatch"],
    facets: { obsession: 0.95, cool: 0.4, moral: 0.45, talk: 0.55, crime: 0.25 },
    summary:
      "A ping-pong hustler in postwar New York tries to will himself into greatness and drags everyone into the grift.",
    why: "Whiplash energy with a con man's mouth. Mastery as a vice, which is the part of your shelf that isn't folk and isn't the mob.",
    vibeLine: "Lean-in. Ambition with dirt under it.",
  }),
  work({
    id: "hamnet",
    name: "Hamnet",
    year: "2025",
    runtime: "2h 5m",
    loved: true,
    family: "grief",
    vibes: ["folk", "dusk"],
    seasons: ["autumn", "winter"],
    facets: { grief: 0.95, folk: 0.45, domestic: 0.6, talk: 0.4, faith: 0.25 },
    summary:
      "Agnes and Will lose a boy, and a play becomes the only place the loss can live. Period England, but the wound is the point.",
    why: "Parenthood and grief without the horror furniture. Lamb and Manchester by the Sea, moved into a Tudor house.",
    vibeLine: "A quiet autumn night. Bring nothing else on.",
  }),
  work({
    id: "bronx-tale",
    name: "A Bronx Tale",
    year: "1993",
    runtime: "2h 1m",
    loved: true,
    family: "crime",
    vibes: ["heat", "rewatch"],
    facets: { crime: 0.75, moral: 0.7, talk: 0.65, comfort: 0.4 },
    summary:
      "A boy in the Bronx is pulled between his bus-driver father and the neighborhood boss who likes him.",
    why: "Moral crime, not a body count. The same choice Sopranos keeps staging, told as one street and one kid.",
    vibeLine: "Heat, but the kind you can rewatch with dinner.",
  }),
  work({
    id: "dead-poets",
    name: "Dead Poets Society",
    year: "1989",
    runtime: "2h 8m",
    loved: true,
    family: "obsession",
    vibes: ["rewatch", "court"],
    seasons: ["autumn"],
    facets: { obsession: 0.55, talk: 0.8, moral: 0.6, grief: 0.45, comfort: 0.5 },
    summary:
      "A new teacher at a strict boys' school asks them to stand on their desks. The school does not thank him.",
    why: "Mentor, language, and a cost. Closer to Whiplash's institution than to a cozy school movie — the poem does not save you.",
    vibeLine: "Autumn term. A rewatch with a last scene that still lands.",
  }),
  work({
    id: "warfare",
    name: "Warfare",
    year: "2025",
    runtime: "1h 35m",
    loved: true,
    family: "war",
    vibes: ["dusk"],
    facets: { war: 0.95, moral: 0.4, obsession: 0.3, domestic: 0.2 },
    summary:
      "One Navy SEAL team, one house, one fight in Iraq, played almost in real time. Procedure, noise, and no speech about what it meant.",
    why: "Dunkirk's craft pulled in tighter. You like war when it refuses the speech. This one barely has a plot on purpose.",
    vibeLine: "Not a comfort night. Short, loud, exact.",
  }),
  work({
    id: "bullitt",
    name: "Bullitt",
    year: "1968",
    runtime: "1h 54m",
    loved: true,
    weight: 0.8,
    family: "cool",
    vibes: ["heat", "rewatch"],
    facets: { cool: 0.9, crime: 0.55, spy: 0.25, moral: 0.3 },
    summary:
      "Steve McQueen is a San Francisco detective who will not perform for the politicians around a witness. Then the Mustang.",
    why: "You wrote Bullet. This is Bullitt — cool as a method, not a pose. The bridge between crime and the Bond films you actually rewatch.",
    vibeLine: "Night drive. Precision over talk.",
  }),
  work({
    id: "thomas-crown",
    name: "The Thomas Crown Affair",
    year: "1968",
    runtime: "1h 42m",
    loved: true,
    weight: 0.8,
    family: "cool",
    vibes: ["summer", "heat"],
    seasons: ["summer"],
    facets: { cool: 0.85, crime: 0.45, euro: 0.25, satire: 0.2 },
    summary:
      "A bored rich man robs a bank because he can, and the investigator starts to enjoy the game.",
    why: "You wrote Thomas Cromwell. This is Thomas Crown — a heist with manners. Ocean's without the crew, McQueen without the Mustang.",
    vibeLine: "Summer cool. A game, not a tragedy.",
  }),
  work({
    id: "promised-land",
    name: "The Promised Land",
    year: "2023",
    runtime: "2h 7m",
    loved: true,
    family: "folk",
    vibes: ["folk", "court"],
    seasons: ["autumn", "winter"],
    facets: { folk: 0.6, moral: 0.85, faith: 0.35, war: 0.35, grief: 0.4 },
    summary:
      "Mads Mikkelsen tries to farm the Jutland heath while a local lord decides the land is not his to give. Danish title Bastarden.",
    why: "Listed under Steve McQueen; read here as the 2023 Mads film, next to The Hunt. Drop it on the Taste page if that was the wrong picture.",
    vibeLine: "Heath, frost, and a man who will not bow.",
  }),
  work({
    id: "american-beauty",
    name: "American Beauty",
    year: "1999",
    runtime: "2h 2m",
    loved: true,
    family: "domestic",
    vibes: ["dusk", "rewatch"],
    seasons: ["autumn"],
    facets: { domestic: 0.8, moral: 0.65, satire: 0.55, grief: 0.4, weird: 0.25 },
    summary:
      "A suburban father quits the performance of his own life. The roses and the bag are doing more work than the plot.",
    why: "Domestic rupture with a joke in its mouth. Not Fight Club's manifesto — a household coming apart in plain sight.",
    vibeLine: "Autumn suburb. Darker than it looks in memory.",
  }),
  work({
    id: "whiplash",
    name: "Whiplash",
    year: "2014",
    runtime: "1h 47m",
    loved: true,
    family: "obsession",
    vibes: ["heat", "rewatch"],
    facets: { obsession: 0.95, moral: 0.5, talk: 0.45, institution: 0.4 },
    summary:
      "A drummer at a conservatory meets the teacher who will bleed the music out of him. The room gets smaller every scene.",
    why: "Mastery against a person. Marty Supreme, Black Swan, Dead Poets — the institution that calls abuse a standard.",
    vibeLine: "Lean-in. One room, one tempo, no mercy.",
  }),
  work({
    id: "fight-club",
    name: "Fight Club",
    year: "1999",
    runtime: "2h 19m",
    loved: true,
    weight: 0.8,
    family: "weird",
    vibes: ["heat"],
    facets: { weird: 0.55, moral: 0.5, satire: 0.6, crime: 0.35, obsession: 0.45 },
    summary:
      "An insomniac and a soap salesman start a club that is not about the club. The twist is the culture now; the rot is still the point.",
    why: "Male rupture, a sermon the film only half believes. You keep it. The deck will not flood you with copies of it.",
    vibeLine: "Night energy. Mean, funny, already half-remembered.",
  }),
  work({
    id: "donnie-darko",
    name: "Donnie Darko",
    year: "2001",
    runtime: "1h 53m",
    loved: true,
    family: "weird",
    vibes: ["folk", "rewatch"],
    seasons: ["autumn"],
    facets: { weird: 0.9, grief: 0.45, domestic: 0.5, faith: 0.25, satire: 0.3 },
    summary:
      "A teenager is told the world ends in twenty-eight days. Suburb, jet engine, rabbit, and a school that explains nothing.",
    why: "Dream logic with a family still in the house. Twin Peaks' small-town wrongness, younger, and set in a hallway you know.",
    vibeLine: "October suburb. Rewatch if you want the feeling, not the diagram.",
  }),
  work({
    id: "it-follows",
    name: "It Follows",
    year: "2014",
    runtime: "1h 40m",
    loved: true,
    family: "folk",
    vibes: ["folk", "dusk"],
    seasons: ["autumn", "summer"],
    facets: { folk: 0.55, weird: 0.6, domestic: 0.4, grief: 0.25, moral: 0.35 },
    summary:
      "Something walks toward you, slowly, and only you can see it. Passing it on is the whole moral problem.",
    why: "Dread without a jump factory. Shape is horror; manners are Lamb — rules, shame, and a suburb that looks ordinary.",
    vibeLine: "Lights low. It does not run.",
  }),
  work({
    id: "crazy-stupid-love",
    name: "Crazy, Stupid, Love",
    year: "2011",
    runtime: "1h 58m",
    loved: true,
    weight: 0.65,
    family: "satire",
    vibes: ["rewatch", "summer"],
    seasons: ["summer"],
    facets: { satire: 0.45, comfort: 0.7, talk: 0.55, domestic: 0.6, moral: 0.3 },
    summary:
      "A marriage cracks in a mall, and a smoother man tries to teach the husband how to be someone else.",
    why: "The warm end of your comedy shelf. Not Superbad, not Stalin — people being foolish because they still want the household.",
    vibeLine: "A lighter night. Romance with a spine.",
  }),
  work({
    id: "death-of-stalin",
    name: "The Death of Stalin",
    year: "2017",
    runtime: "1h 47m",
    loved: true,
    family: "satire",
    vibes: ["heat", "court"],
    facets: { satire: 0.95, moral: 0.7, court: 0.55, talk: 0.75, crime: 0.35 },
    summary:
      "Stalin dies and the men around the body start the next regime before the corpse is cold. Panic in good tailoring.",
    why: "Vicious comedy about power. Court intrigue with a joke that knows someone is about to be shot.",
    vibeLine: "Mean laughter. A committee as a crime family.",
  }),
  work({
    id: "oceans",
    name: "Ocean's Eleven",
    year: "2001–2007",
    runtime: "one film of the trilogy",
    loved: true,
    family: "cool",
    vibes: ["rewatch", "summer", "heat"],
    seasons: ["summer"],
    facets: { cool: 0.9, crime: 0.55, comfort: 0.75, satire: 0.35, talk: 0.4 },
    summary:
      "Danny Ocean gets out and collects a crew to take a casino. The trilogy is the love — start wherever the mood is.",
    why: "Comfort heist. Thomas Crown's game, played by friends. A rewatch night when you want craft without grief.",
    vibeLine: "Rewatch. Suits, timing, no one important dies.",
  }),
  work({
    id: "batman-nolan",
    name: "Nolan's Batman",
    year: "2005–2012",
    runtime: "one film of the trilogy",
    loved: true,
    weight: 0.85,
    family: "cool",
    vibes: ["rewatch", "dusk", "heat"],
    facets: { cool: 0.7, moral: 0.65, crime: 0.55, institution: 0.45, comfort: 0.6, obsession: 0.35 },
    summary:
      "Begins, The Dark Knight, Rises. A city as a moral argument, dressed as a blockbuster you already know by heart.",
    why: "Spectacle you respect because the question is about order, not the toy. Comfort, but not empty.",
    vibeLine: "Rewatch. A long one, city lights, a known ending.",
  }),
  work({
    id: "harry-potter",
    name: "Harry Potter",
    year: "2001–2011",
    runtime: "one film of the sequence",
    loved: true,
    family: "comfort",
    vibes: ["rewatch"],
    seasons: ["autumn", "winter"],
    facets: { comfort: 0.95, folk: 0.45, court: 0.25, grief: 0.35, weird: 0.3 },
    summary:
      "The sequence, from the cupboard to the battle. Pick the year you want. Autumn is the honest season for it.",
    why: "You named this as fall rewatch weather, next to The Americans and Lamb. Comfort with a school, a death, and a house that remembers you.",
    vibeLine: "October rewatch. Start at the one you miss, not at the beginning.",
  }),
  work({
    id: "lotr",
    name: "The Lord of the Rings",
    year: "2001–2003",
    runtime: "one film of the trilogy",
    loved: true,
    family: "comfort",
    vibes: ["rewatch", "folk"],
    seasons: ["autumn", "winter"],
    facets: { comfort: 0.9, war: 0.55, folk: 0.5, faith: 0.35, moral: 0.6, grief: 0.4 },
    summary:
      "Fellowship, Towers, Return. Fellowship if you want friends on a road. Return if you want the cost.",
    why: "Saga comfort that still believes in sacrifice. A winter rewatch, not a discovery.",
    vibeLine: "Rewatch. Firelight, a long road, a known grief.",
  }),
  work({
    id: "lamb",
    name: "Lamb",
    year: "2021",
    runtime: "1h 46m",
    loved: true,
    family: "folk",
    vibes: ["folk"],
    seasons: ["autumn", "winter"],
    facets: { folk: 0.95, grief: 0.85, domestic: 0.6, faith: 0.3, weird: 0.45 },
    summary:
      "A couple on an Icelandic farm find something in the barn and decide it is theirs. Almost no music tells you how to feel.",
    why: "The anchor. Parenthood, folk dread, austerity. The whole folk side of the deck is measured against this, not against slashers.",
    vibeLine: "Fog, a barn, no sermon. The Lamb night.",
  }),
  work({
    id: "hereditary",
    name: "Hereditary",
    year: "2018",
    runtime: "2h 7m",
    loved: true,
    family: "domestic",
    vibes: ["folk", "dusk"],
    seasons: ["autumn"],
    facets: { domestic: 0.75, grief: 0.9, folk: 0.7, weird: 0.55, faith: 0.35 },
    summary:
      "A family starts to come apart after a funeral, and the house has older plans than their therapy.",
    why: "Grief horror with a family argument still audible under the cult. Heavier than Lamb, meaner than Servant, same wound.",
    vibeLine: "Not a casual night. Family, then the floor drops.",
  }),
  work({
    id: "american-pie",
    name: "American Pie",
    year: "1999–2003",
    runtime: "one film of the trilogy",
    loved: true,
    weight: 0.55,
    family: "satire",
    vibes: ["rewatch", "summer"],
    seasons: ["summer"],
    facets: { satire: 0.7, comfort: 0.65, talk: 0.3 },
    summary: "The trilogy. Crude on purpose, sentimental underneath, best when you already know the jokes.",
    why: "Youth raunch you actually like, with Superbad. The deck will not pretend this is Lamb. It is a summer rewatch or nothing.",
    vibeLine: "Light, dumb, yours. A palate cleanse, not a taste.",
  }),
  work({
    id: "superbad",
    name: "Superbad",
    year: "2007",
    runtime: "1h 53m",
    loved: true,
    weight: 0.6,
    family: "satire",
    vibes: ["rewatch", "summer"],
    seasons: ["summer"],
    facets: { satire: 0.75, comfort: 0.6, talk: 0.45 },
    summary: "Two friends try to get to a party before high school ends and the friendship has to change shape.",
    why: "The sincere one inside the raunch. A rewatch, not a clue about folk horror.",
    vibeLine: "Summer noise. Friendship, panic, a bad plan.",
  }),
  work({
    id: "skyfall",
    name: "Skyfall",
    year: "2012",
    runtime: "2h 23m",
    loved: true,
    weight: 0.32,
    family: "spy",
    vibes: ["dusk", "rewatch"],
    seasons: ["autumn"],
    facets: { spy: 0.85, cool: 0.6, grief: 0.4, moral: 0.45, comfort: 0.4 },
    summary: "Bond is shot, comes back old, and goes home to a house in Scotland. The autumn Bond.",
    why: "One of seven Bonds on your list, weighted as a cluster so they don't drown Lamb. This is the dusk one.",
    vibeLine: "Autumn spy. A house, a mother-figure, a last stand.",
  }),
  work({
    id: "casino-royale",
    name: "Casino Royale",
    year: "2006",
    runtime: "2h 24m",
    loved: true,
    weight: 0.36,
    family: "spy",
    vibes: ["summer", "dusk", "rewatch"],
    seasons: ["summer"],
    facets: { spy: 0.9, euro: 0.55, cool: 0.7, moral: 0.4, grief: 0.35 },
    summary: "Bond before the pose, bleeding in a stairwell, then in love at a poker table in Montenegro.",
    why: "Listed twice for a reason: it is both a Bond and a euro-summer film. Heat, water, and a feeling he is not supposed to have.",
    vibeLine: "Late summer. Beautiful, and it ends badly.",
  }),
  work({
    id: "tomorrow-never-dies",
    name: "Tomorrow Never Dies",
    year: "1997",
    runtime: "1h 59m",
    loved: true,
    weight: 0.28,
    family: "spy",
    vibes: ["rewatch", "heat"],
    facets: { spy: 0.7, cool: 0.55, comfort: 0.45 },
    summary: "A media baron starts a war for the exclusive. Bond and a Chinese agent steal a car and a night.",
    why: "The playful Bond on your list. Craft and a chase, not a tragedy.",
    vibeLine: "Rewatch when you want the machine, not the mood.",
  }),
  work({
    id: "goldfinger",
    name: "Goldfinger",
    year: "1964",
    runtime: "1h 50m",
    loved: true,
    weight: 0.3,
    family: "spy",
    vibes: ["rewatch", "summer"],
    facets: { spy: 0.75, cool: 0.8, comfort: 0.55, satire: 0.25 },
    summary: "The template: gold, a laser, a crime that is almost a joke. Connery already bored of being impressed.",
    why: "Cool as lineage. Thomas Crown and Bullitt inherit this shrug.",
    vibeLine: "Classic rewatch. Style first.",
  }),
  work({
    id: "spectre",
    name: "Spectre",
    year: "2015",
    runtime: "2h 28m",
    loved: true,
    weight: 0.26,
    family: "spy",
    vibes: ["dusk", "rewatch"],
    facets: { spy: 0.7, cool: 0.5, institution: 0.35, comfort: 0.35 },
    summary: "Bond goes after the author of his own story, through Mexico, Rome, and a clinic in the Alps.",
    why: "You kept it on the list. It is the connective Bond — less sharp than Casino Royale, still part of the craft cluster.",
    vibeLine: "A long spy night. Rome in the middle.",
  }),
  work({
    id: "live-and-let-die",
    name: "Live and Let Die",
    year: "1973",
    runtime: "2h 1m",
    loved: true,
    weight: 0.28,
    family: "spy",
    vibes: ["summer", "rewatch"],
    seasons: ["summer"],
    facets: { spy: 0.65, cool: 0.5, weird: 0.35, comfort: 0.4 },
    summary: "Moore's first Bond, tarot and boats in Louisiana, a villain who believes his own religion.",
    why: "The strange Bond. A little folk at the edges of the tuxedo — which is why it survived on your list.",
    vibeLine: "Summer oddity. Boats, cards, a grin.",
  }),
  work({
    id: "no-time-to-die",
    name: "No Time to Die",
    year: "2021",
    runtime: "2h 43m",
    loved: true,
    weight: 0.3,
    family: "spy",
    vibes: ["dusk"],
    seasons: ["autumn"],
    facets: { spy: 0.75, grief: 0.55, moral: 0.45, cool: 0.4 },
    summary: "Bond is done, then isn't. A last film about whether a man in this job gets to have a life.",
    why: "The grief Bond. Closer to Skyfall's house than to Goldfinger's joke.",
    vibeLine: "Dusk. An ending, so only if you want one.",
  }),
  work({
    id: "style-woody",
    name: "Woody Allen",
    year: "",
    runtime: "",
    loved: true,
    hidden: true,
    weight: 0.9,
    family: "euro",
    vibes: ["summer"],
    facets: { talk: 0.85, euro: 0.55, moral: 0.6, satire: 0.65, domestic: 0.4 },
    summary: "The mode, not one film.",
    why: "Hidden anchor so the talky, guilty, sometimes-European comedies pull the shelf without pretending you named forty titles.",
    vibeLine: "",
  }),
  work({
    id: "vicky-cristina",
    name: "Vicky Cristina Barcelona",
    year: "2008",
    runtime: "1h 36m",
    loved: true,
    family: "euro",
    vibes: ["summer"],
    seasons: ["summer"],
    facets: { euro: 0.95, talk: 0.8, satire: 0.45, moral: 0.4, comfort: 0.35 },
    summary:
      "Two Americans in Barcelona get pulled into an artist's life and then his ex-wife's. Summer, desire, and talk that goes too far.",
    why: "The Woody film you named. Euro summer as a moral mess with good light, not as a postcard.",
    vibeLine: "Hot stone, a villa, people saying the unsafe thing.",
  }),
  work({
    id: "raging-bull",
    name: "Raging Bull",
    year: "1980",
    runtime: "2h 9m",
    loved: true,
    weight: 0.55,
    family: "obsession",
    vibes: ["heat"],
    facets: { obsession: 0.85, crime: 0.35, moral: 0.6, grief: 0.55, cool: 0.3 },
    summary: "Jake LaMotta in the ring and at the table, destroying the people who stay. Black and white, and mean at home.",
    why: "Scorsese when the subject is the body and the jealousy, not the crew. Whiplash's cousin, with no teacher to blame.",
    vibeLine: "Heat without glamour. A man who cannot stop.",
  }),
  work({
    id: "casino",
    name: "Casino",
    year: "1995",
    runtime: "2h 58m",
    loved: true,
    weight: 0.55,
    family: "crime",
    vibes: ["heat"],
    facets: { crime: 0.9, cool: 0.45, moral: 0.4, talk: 0.55, obsession: 0.4 },
    summary: "Las Vegas skim, a marriage made of money, and the voiceover that already knows how it ends.",
    why: "Goodfellas' colder twin. You like the business of crime as much as the friendship.",
    vibeLine: "A long heat night. Count the money, then the bodies.",
  }),
  work({
    id: "goodfellas",
    name: "Goodfellas",
    year: "1990",
    runtime: "2h 25m",
    loved: true,
    weight: 0.7,
    family: "crime",
    vibes: ["heat", "rewatch"],
    facets: { crime: 0.95, cool: 0.5, talk: 0.6, moral: 0.45, comfort: 0.4 },
    summary: "Henry Hill wants to be a gangster, and for a while the film agrees with him. Then the helicopters.",
    why: "The other pole from Lamb. Appetite, talk, loyalty that was always a transaction. The crime side of the deck answers to this.",
    vibeLine: "Heat. Copacabana night, or the coke night. You know which.",
  }),
  work({
    id: "gangs-of-new-york",
    name: "Gangs of New York",
    year: "2002",
    runtime: "2h 47m",
    loved: true,
    weight: 0.5,
    family: "crime",
    vibes: ["heat", "court"],
    facets: { crime: 0.7, war: 0.45, court: 0.35, moral: 0.5, faith: 0.3 },
    summary: "Five Points, a boy back for his father, and a city about to be drafted into a larger war.",
    why: "You wrote NY Gangs. Historical crime — the street as a nation, which is also Boardwalk and Gangs' own priest problem.",
    vibeLine: "Heat with mud on it. A long one.",
  }),
  work({
    id: "the-departed",
    name: "The Departed",
    year: "2006",
    runtime: "2h 31m",
    loved: true,
    weight: 0.6,
    family: "crime",
    vibes: ["heat", "dusk"],
    facets: { crime: 0.85, moral: 0.6, spy: 0.35, talk: 0.5, institution: 0.4 },
    summary: "A cop in the gang, a gangster in the police, Boston as a small town with badges.",
    why: "Crime plus the double life, which is your spy shelf leaking into Scorsese. Identity under pressure.",
    vibeLine: "Dusk heat. Phones, roofs, nobody clean.",
  }),
  work({
    id: "bone-collector",
    name: "The Bone Collector",
    year: "1999",
    runtime: "1h 58m",
    loved: true,
    weight: 0.45,
    family: "crime",
    vibes: ["dusk"],
    facets: { crime: 0.6, institution: 0.35, obsession: 0.4, moral: 0.3 },
    summary: "A paralyzed detective and a young cop work a killer through a radio and a grid of New York clues.",
    why: "Procedural, which you also keep via The Killing and The Bone Collector's puzzle. Not the taste's center. A rewatch when you want the case.",
    vibeLine: "A case night. Clues, not myth.",
  }),
  work({
    id: "interstellar",
    name: "Interstellar",
    year: "2014",
    runtime: "2h 49m",
    loved: true,
    weight: 0.45,
    family: "weird",
    vibes: ["rewatch", "dusk"],
    facets: { weird: 0.55, grief: 0.6, moral: 0.45, obsession: 0.5, comfort: 0.35, faith: 0.2 },
    summary: "A father leaves Earth through a wormhole because the children will starve. Time is the villain that loves him back.",
    why: "Nolan when the engine is grief, not the heist. Parenthood again — your quiet theme, here with a spaceship.",
    vibeLine: "A long rewatch. Father and clock.",
  }),
  work({
    id: "passion",
    name: "The Passion of the Christ",
    year: "2004",
    runtime: "2h 7m",
    loved: true,
    weight: 0.75,
    family: "faith",
    vibes: ["folk"],
    seasons: ["winter"],
    facets: { faith: 0.95, grief: 0.7, war: 0.35, moral: 0.5 },
    summary: "The last hours, in Aramaic, with the body as the argument. Not a gentle holy week film.",
    why: "Faith on your shelf is austere and physical — Leviathan, this, not a lesson with a smile. The deck treats preachy as a penalty; this one you already chose.",
    vibeLine: "Only if you want the weight. Not a mood pick.",
  }),
  work({
    id: "dunkirk",
    name: "Dunkirk",
    year: "2017",
    runtime: "1h 46m",
    loved: true,
    weight: 0.5,
    family: "war",
    vibes: ["dusk", "rewatch"],
    facets: { war: 0.9, cool: 0.45, moral: 0.4, obsession: 0.3 },
    summary: "The evacuation told as three clocks: the mole, the sea, the air. Almost no backstory. The ticking is the script.",
    why: "War as craft. Warfare's older brother. Nolan without the speech about feelings, until the reading of the newspaper.",
    vibeLine: "Tight, loud, short. A dusk you can finish.",
  }),
  work({
    id: "inception",
    name: "Inception",
    year: "2010",
    runtime: "2h 28m",
    loved: true,
    weight: 0.45,
    family: "weird",
    vibes: ["rewatch", "heat"],
    facets: { weird: 0.7, cool: 0.65, grief: 0.45, obsession: 0.5, crime: 0.3 },
    summary: "A thief steals through dreams and is hired to plant an idea. The job is also a marriage he cannot leave.",
    why: "Puzzle craft you love, with a grief hiding in the mechanism. Prestige and Arrival live next door.",
    vibeLine: "Rewatch for the architecture. Stay for the guilt.",
  }),
  work({
    id: "gone-with-the-wind",
    name: "Gone with the Wind",
    year: "1939",
    runtime: "3h 58m",
    loved: true,
    weight: 0.7,
    family: "court",
    vibes: ["court", "rewatch"],
    facets: { court: 0.75, war: 0.55, moral: 0.45, comfort: 0.4, grief: 0.5, talk: 0.4 },
    summary: "Scarlett will not be poor, and the war takes the world that made that sentence possible. A full evening, not a whim.",
    why: "Scale and want. Court and ruin — the same muscle as The Age of Innocence, ruder and longer.",
    vibeLine: "Only when you have the night. A rewatch with an intermission.",
  }),
  work({
    id: "age-of-innocence",
    name: "The Age of Innocence",
    year: "1993",
    runtime: "2h 19m",
    loved: true,
    weight: 0.75,
    family: "court",
    vibes: ["court", "summer"],
    seasons: ["summer", "autumn"],
    facets: { court: 0.85, talk: 0.7, moral: 0.65, euro: 0.35, grief: 0.45, cool: 0.3 },
    summary:
      "Newland Archer is engaged to the right woman and in love with the wrong one. New York society does the violence with invitations.",
    why: "Scorsese without a gun. Manners as the mob. This is how your crime shelf and your period shelf are the same taste.",
    vibeLine: "Lamps, gloves, a feeling nobody is allowed to finish.",
  }),
  work({
    id: "the-witch",
    name: "The Witch",
    year: "2015",
    runtime: "1h 32m",
    loved: true,
    family: "folk",
    vibes: ["folk"],
    seasons: ["autumn", "winter"],
    facets: { folk: 0.95, faith: 0.7, domestic: 0.65, grief: 0.55, weird: 0.4 },
    summary:
      "A Puritan family banished to the edge of the wood starts to lose the children, the crop, and the story they tell about God.",
    why: "Folk and faith in one house. Lamb's austerity, with a theology that is the horror instead of a twist.",
    vibeLine: "Grey field. The folk night, stricter than Lamb.",
  }),
  work({
    id: "another-round",
    name: "Another Round",
    year: "2020",
    runtime: "1h 57m",
    loved: true,
    family: "satire",
    vibes: ["dusk", "rewatch"],
    facets: { satire: 0.45, moral: 0.6, talk: 0.65, grief: 0.5, euro: 0.35, comfort: 0.3 },
    summary:
      "Four teachers test the theory that life is better with a constant low dose of alcohol. It works, and then it is a tragedy.",
    why: "Mads, melancholy, a joke that becomes a life. The Hunt's director, softer, still unwilling to flatter them.",
    vibeLine: "Evening with friends. The dance at the end earns the rest.",
  }),
  work({
    id: "prestige",
    name: "The Prestige",
    year: "2006",
    runtime: "2h 10m",
    loved: true,
    weight: 0.5,
    family: "obsession",
    vibes: ["dusk", "rewatch"],
    facets: { obsession: 0.9, weird: 0.45, moral: 0.55, cool: 0.5, crime: 0.25 },
    summary: "Two magicians in London ruin their lives trying to own one trick. The pledge, the turn, the prestige.",
    why: "Nolan as obsession, which is your Whiplash register. A rewatch you can still argue about after.",
    vibeLine: "Dusk puzzle. Don't explain it to the room.",
  }),
  work({
    id: "arrival",
    name: "Arrival",
    year: "2016",
    runtime: "1h 56m",
    loved: true,
    family: "weird",
    vibes: ["dusk", "folk"],
    facets: { weird: 0.65, grief: 0.75, talk: 0.7, moral: 0.55, faith: 0.25 },
    summary: "A linguist is asked to talk to whatever landed. The language changes what a sentence can do to a life.",
    why: "Grief and a system of meaning. Not a war-of-the-worlds film. Closer to Hamnet and Interstellar than to spectacle.",
    vibeLine: "Quiet dusk. Words, a child, a choice.",
  }),
  work({
    id: "once-upon-america",
    name: "Once Upon a Time in America",
    year: "1984",
    runtime: "3h 49m",
    loved: true,
    weight: 0.8,
    family: "crime",
    vibes: ["heat", "dusk"],
    facets: { crime: 0.85, grief: 0.6, moral: 0.55, euro: 0.2, talk: 0.4 },
    summary: "Jewish boys in New York become gangsters, and an old man tries to remember which betrayal was his. A long evening.",
    why: "Crime as memory and regret, not as a good time. The anti-Goodfellas on the same shelf — you kept both.",
    vibeLine: "Only with the whole night. Opium, friendship, the bill.",
  }),
  work({
    id: "the-hunt",
    name: "The Hunt",
    year: "2012",
    runtime: "1h 55m",
    loved: true,
    family: "grief",
    vibes: ["dusk", "folk"],
    seasons: ["autumn", "winter"],
    facets: { moral: 0.95, grief: 0.7, talk: 0.6, domestic: 0.55, faith: 0.35 },
    summary:
      "A kindergarten teacher in a Danish town is accused of the worst thing. The community decides before the facts do.",
    why: "Mads, judgment, a small town that would rather be certain. Leviathan's cousin, without the mayor's office.",
    vibeLine: "Winter village. Hard to watch, which is the point.",
  }),
  work({
    id: "manchester",
    name: "Manchester by the Sea",
    year: "2016",
    runtime: "2h 17m",
    loved: true,
    family: "grief",
    vibes: ["dusk", "folk"],
    seasons: ["winter"],
    facets: { grief: 0.95, domestic: 0.6, moral: 0.5, talk: 0.45 },
    summary: "A janitor goes home when his brother dies and is asked to raise the boy. He is not able to become that man.",
    why: "Grief that does not redeem. Hamnet weeps toward art. This one refuses the third act you might want.",
    vibeLine: "Cold harbor. No lesson at the end.",
  }),
  work({
    id: "the-killing",
    name: "The Killing",
    year: "2007",
    kind: "series",
    runtime: "one episode",
    loved: true,
    family: "crime",
    vibes: ["dusk", "folk"],
    seasons: ["autumn", "winter"],
    facets: { crime: 0.7, moral: 0.75, grief: 0.65, talk: 0.5, institution: 0.4 },
    summary: "The Danish one. A detective and a family, a murdered girl, a case that ruins the people solving it. Copenhagen rain.",
    why: "Procedure with a moral cost. The Bridge, The Hunt, and your Apple legal dramas all answer to this weather.",
    vibeLine: "Rain. One episode if you are tired, a run if you are not.",
  }),
  work({
    id: "hannibal",
    name: "Hannibal",
    year: "2013",
    kind: "series",
    runtime: "one episode",
    loved: true,
    family: "weird",
    vibes: ["folk", "dusk"],
    facets: { weird: 0.7, crime: 0.55, faith: 0.25, obsession: 0.65, cool: 0.45, moral: 0.4 },
    summary: "Will Graham profiles killers and eats dinner with the one he cannot see. Baroque, awful, and oddly tender.",
    why: "Horror as taste and friendship. Not Lamb's austerity — the ornate twin. Mindhunter is the dry version, on the new shelf.",
    vibeLine: "A rich, uneasy episode. Not while you eat, unless you mean to.",
  }),
  work({
    id: "true-detective",
    name: "True Detective",
    year: "2014",
    kind: "series",
    runtime: "season one",
    loved: true,
    family: "folk",
    vibes: ["folk", "dusk"],
    seasons: ["autumn", "winter"],
    facets: { folk: 0.6, crime: 0.7, moral: 0.65, weird: 0.45, talk: 0.55, faith: 0.3 },
    summary: "Season one only, on your list. Two Louisiana detectives, a cult in the cane, a time jump that makes them liars.",
    why: "Crime wearing folk horror's mask. From is the maze you still watch. This is the season where the philosophy and the body both count.",
    vibeLine: "Flat land, yellow light, a long conversation in a car.",
  }),
  work({
    id: "fargo",
    name: "Fargo",
    year: "2014",
    kind: "series",
    runtime: "season one",
    loved: true,
    family: "crime",
    vibes: ["dusk", "folk"],
    seasons: ["winter"],
    facets: { crime: 0.75, satire: 0.55, moral: 0.6, folk: 0.3, weird: 0.35 },
    summary: "Season one. A mild man in Minnesota meets a drifter who is not mild, and the snow covers the rest.",
    why: "Coen moral comedy stretched into a season. Death of Stalin's cousin in a nicer voice: violence, politeness, consequence.",
    vibeLine: "Winter. Polite, then not.",
  }),
  work({
    id: "breaking-bad",
    name: "Breaking Bad",
    year: "2008",
    kind: "series",
    runtime: "one episode",
    loved: true,
    weight: 0.85,
    family: "crime",
    vibes: ["heat", "rewatch"],
    facets: { crime: 0.85, moral: 0.8, obsession: 0.55, domestic: 0.5, talk: 0.4 },
    summary: "A chemistry teacher decides pride is a better death than cancer. The family is who pays.",
    why: "Moral decay inside a household. You have the whole crime canon. This is the one about a man choosing to become the villain.",
    vibeLine: "Heat. An episode, or the slide you already know.",
  }),
  work({
    id: "mad-men",
    name: "Mad Men",
    year: "2007",
    kind: "series",
    runtime: "one episode",
    loved: true,
    family: "court",
    vibes: ["dusk", "rewatch"],
    seasons: ["autumn"],
    facets: { talk: 0.85, moral: 0.6, cool: 0.55, domestic: 0.5, satire: 0.35, comfort: 0.4 },
    summary: "Advertising men in the sixties perform being fine. The work is the costume. The marriage is the plot.",
    why: "Talk, double lives, a beautiful surface over a moral mess. The Americans without the spy excuse — or with a different one.",
    vibeLine: "Dusk rewatch. One episode, a drink, no rush.",
  }),
  work({
    id: "the-americans",
    name: "The Americans",
    year: "2013",
    kind: "series",
    runtime: "one episode",
    loved: true,
    family: "spy",
    vibes: ["dusk", "rewatch"],
    seasons: ["autumn"],
    facets: { spy: 0.95, moral: 0.85, domestic: 0.8, grief: 0.45, talk: 0.55, faith: 0.2 },
    summary: "Two Soviet illegals in Reagan's Washington raise children and bury people in the same week. The marriage is the operation.",
    why: "The dusk anchor. Fall, you said, is this — secrecy inside a family, craft, and a bill that comes due. The spy shelf is measured here, not on gadget Bond.",
    vibeLine: "October. Kitchen light, a wig, a conversation they shouldn't survive.",
  }),
  work({
    id: "medici",
    name: "Medici",
    year: "2016",
    kind: "series",
    runtime: "one episode",
    loved: true,
    weight: 0.7,
    family: "court",
    vibes: ["court", "summer"],
    seasons: ["summer"],
    facets: { court: 0.85, crime: 0.35, faith: 0.3, moral: 0.45, euro: 0.4 },
    summary: "Florence, the bank, the family that buys a republic and calls it patronage.",
    why: "Court as a business. Tudors, Plantagenets, Age of Innocence — power in clothes, here with better stone.",
    vibeLine: "Warm stone. Intrigue you can leave after one episode.",
  }),
  work({
    id: "band-of-brothers",
    name: "Band of Brothers",
    year: "2001",
    kind: "series",
    runtime: "one episode",
    loved: true,
    family: "war",
    vibes: ["rewatch", "dusk"],
    seasons: ["autumn", "winter"],
    facets: { war: 0.95, moral: 0.6, grief: 0.5, comfort: 0.35, talk: 0.3 },
    summary: "Easy Company from training to the Eagle's Nest. The interviews with the real men are part of the memory of it.",
    why: "War you rewatch because of the unit, not the battle. Dunkirk is the clock. This is the friendship.",
    vibeLine: "A known episode on a cold night. Currahee, or the one you avoid.",
  }),
  work({
    id: "boardwalk",
    name: "Boardwalk Empire",
    year: "2010",
    kind: "series",
    runtime: "one episode",
    loved: true,
    weight: 0.75,
    family: "crime",
    vibes: ["heat", "court"],
    facets: { crime: 0.85, court: 0.45, moral: 0.5, cool: 0.4, talk: 0.45 },
    summary: "Atlantic City, Prohibition, a treasurer who is also the gangster. Politics and booze as the same ledger.",
    why: "Goodfellas slowed down and put in a suit. Historical crime, which is half your shelf.",
    vibeLine: "Heat in winter clothes. One careful episode.",
  }),
  work({
    id: "entourage",
    name: "Entourage",
    year: "2004",
    kind: "series",
    runtime: "one episode",
    loved: true,
    weight: 0.4,
    family: "satire",
    vibes: ["summer", "rewatch"],
    seasons: ["summer"],
    facets: { satire: 0.45, comfort: 0.7, cool: 0.4, talk: 0.35 },
    summary: "An actor and his friends from Queens take Hollywood as a group sport. Light on purpose.",
    why: "Kept small in the math so it doesn't pull the whole shelf toward hangout TV. A summer rewatch when the day was enough.",
    vibeLine: "Easy. Sun, insults, nothing at stake.",
  }),
  work({
    id: "sopranos",
    name: "The Sopranos",
    year: "1999",
    kind: "series",
    runtime: "one episode",
    loved: true,
    family: "crime",
    vibes: ["heat", "dusk", "rewatch"],
    facets: { crime: 0.9, domestic: 0.75, moral: 0.8, talk: 0.7, grief: 0.4, satire: 0.3 },
    summary: "A New Jersey boss starts therapy because the panic attacks are bad for business. The family at home is the other crew.",
    why: "The crime anchor that is also a marriage. Goodfellas is the rise. This is the life after you got what you wanted and it made you sick.",
    vibeLine: "Dusk heat. Therapy, gravy, a dream you don't explain.",
  }),
  work({
    id: "the-wire",
    name: "The Wire",
    year: "2002",
    kind: "series",
    runtime: "one episode",
    loved: true,
    family: "institution",
    vibes: ["heat", "dusk"],
    facets: { institution: 0.9, crime: 0.75, moral: 0.85, talk: 0.65, grief: 0.35 },
    summary: "Baltimore as a set of systems: corners, police, docks, city hall, schools, the paper. People are what the system spends.",
    why: "Institution over myth. Severance is the surreal office. This is the real one, and you already did the work of watching it.",
    vibeLine: "A serious episode. The case is the city.",
  }),
  work({
    id: "tudors",
    name: "The Tudors",
    year: "2007",
    kind: "series",
    runtime: "one episode",
    loved: true,
    weight: 0.7,
    family: "court",
    vibes: ["court"],
    facets: { court: 0.9, faith: 0.45, moral: 0.4, crime: 0.3, euro: 0.2 },
    summary: "Henry, the marriages, the ministers who think they can manage a king. Sex and execution on a short fuse.",
    why: "Court as appetite. Wolf Hall, on the new shelf, is the colder Cromwell. This is the one you already live with.",
    vibeLine: "Court. Jewels, then the axe.",
  }),
  work({
    id: "plantagenets",
    name: "The Plantagenets",
    year: "documentary",
    kind: "series",
    runtime: "one part",
    loved: true,
    weight: 0.55,
    family: "court",
    vibes: ["court", "rewatch"],
    facets: { court: 0.8, war: 0.45, faith: 0.3, talk: 0.5 },
    summary: "The YouTube history you already use. Dynasty, murder, and the long English argument about who gets the crown.",
    why: "Background court. It anchors the period shelf so Wolf Hall and Rome have somewhere to stand. A rewatch, not a premiere.",
    vibeLine: "Background on a quiet night. Maps and bad kings.",
  }),
  work({
    id: "fringe",
    name: "Fringe",
    year: "2008",
    kind: "series",
    runtime: "one episode",
    loved: true,
    family: "weird",
    vibes: ["rewatch", "dusk"],
    facets: { weird: 0.85, institution: 0.45, grief: 0.5, moral: 0.45, comfort: 0.55, faith: 0.15 },
    summary: "An FBI agent, a mad scientist, and his son investigate cases that break physics. It becomes a story about a father.",
    why: "You were rewatching it. Pattern mysteries that turn into family. The comfort weird, next to Twin Peaks' harsher dream.",
    vibeLine: "Rewatch. One case, then the mythology if you want it.",
  }),
  work({
    id: "twin-peaks-return",
    name: "Twin Peaks: The Return",
    year: "2017",
    kind: "series",
    runtime: "one part",
    loved: true,
    family: "weird",
    vibes: ["folk", "dusk"],
    facets: { weird: 0.95, folk: 0.45, grief: 0.4, moral: 0.35, domestic: 0.3 },
    summary: "Twenty-five years later, and the town is not the comfort people misremember. Dougie, the arm, a nuclear test, a long drive.",
    why: "Dream logic you stayed with. Not a cozy mystery. The deck uses this as the far end of weird, so it doesn't recommend puzzle clones.",
    vibeLine: "Only if you want to be lost. Not a tonight for tired.",
  }),
  work({
    id: "from",
    name: "From",
    year: "2022",
    kind: "series",
    runtime: "one episode",
    loved: true,
    weight: 0.65,
    family: "weird",
    vibes: ["folk", "dusk"],
    facets: { weird: 0.7, folk: 0.55, domestic: 0.4, moral: 0.35, institution: 0.2 },
    summary: "A town you cannot leave, things in the dark, and a mythology that keeps adding doors. You are in it, including season four.",
    why: "Kept, and ranked under Widow's Bay. The maze is real for you. The deck will not assume it is the peak of the folk shelf.",
    vibeLine: "If you are mid-season, this is the rewatch. Otherwise let it cool.",
  }),
  work({
    id: "severance",
    name: "Severance",
    year: "2022",
    kind: "series",
    runtime: "one episode",
    loved: true,
    family: "institution",
    vibes: ["dusk", "rewatch"],
    facets: { institution: 0.95, weird: 0.7, moral: 0.6, cool: 0.45, grief: 0.35 },
    summary: "A company splits your memory so the work-you never meets the home-you. The office is polite and wrong.",
    why: "The institution anchor. Sterile surreal, identity as an HR policy. Devs and Counterpart, on the shelf, have to beat this.",
    vibeLine: "Fluorescent dusk. One episode if the day already felt like an office.",
  }),
  work({
    id: "silo",
    name: "Silo",
    year: "2023",
    kind: "series",
    runtime: "one episode",
    loved: true,
    weight: 0.8,
    family: "institution",
    vibes: ["dusk"],
    facets: { institution: 0.85, moral: 0.55, weird: 0.4, spy: 0.25, faith: 0.2 },
    summary: "Humanity lives in a buried silo and is not allowed to ask what the outside is. A sheriff starts asking anyway.",
    why: "Institutional mystery with a physical world. Severance is the mind. This is the staircase. Same love of a rule that is a lie.",
    vibeLine: "Dusk bunker. One episode down the stairs.",
  }),
  work({
    id: "presumed-innocent",
    name: "Presumed Innocent",
    year: "2024",
    kind: "series",
    runtime: "one episode",
    loved: true,
    weight: 0.7,
    family: "crime",
    vibes: ["dusk"],
    facets: { crime: 0.6, moral: 0.7, domestic: 0.55, talk: 0.6, institution: 0.45 },
    summary: "A prosecutor is accused of murdering the colleague he was sleeping with. The marriage watches the trial.",
    why: "Legal dread inside a household. The Killing's question — who do you become in a case — moved into an American marriage.",
    vibeLine: "One tense episode. Not if you wanted to relax.",
  }),
  work({
    id: "defending-jacob",
    name: "Defending Jacob",
    year: "2020",
    kind: "series",
    runtime: "one episode",
    loved: true,
    weight: 0.75,
    family: "grief",
    vibes: ["dusk", "folk"],
    facets: { grief: 0.7, moral: 0.75, domestic: 0.8, crime: 0.55, talk: 0.45 },
    summary: "A prosecutor's son is accused of killing a classmate. The parents have to decide what they are willing to know.",
    why: "Parenthood as moral horror without a monster in the barn. Lamb's question in a courtroom: what will you protect, and what is it.",
    vibeLine: "Family dread. A suburban night, no supernatural required.",
  }),
  work({
    id: "black-bird",
    name: "Black Bird",
    year: "2022",
    kind: "series",
    runtime: "one episode",
    loved: true,
    weight: 0.7,
    family: "crime",
    vibes: ["dusk"],
    facets: { crime: 0.7, moral: 0.65, talk: 0.6, institution: 0.4, grief: 0.35 },
    summary: "A convict is offered freedom if he can draw a confession out of a suspected serial killer in the next cell.",
    why: "Two-handed dread. Hannibal's intimacy without the opera — a limited run, which suits a tonight better than a mythology.",
    vibeLine: "A short series. Talk in a cell.",
  }),
  work({
    id: "drops-of-god",
    name: "Drops of God",
    year: "2023",
    kind: "series",
    runtime: "one episode",
    loved: true,
    family: "obsession",
    vibes: ["summer", "court"],
    seasons: ["summer"],
    facets: { obsession: 0.7, euro: 0.55, talk: 0.5, moral: 0.35, comfort: 0.3, grief: 0.35 },
    summary: "A father's wine legacy splits between his daughter and his star pupil. Taste is the contest. Family is the wound.",
    why: "Obsession with a sensual craft, euro light, inheritance. The Taste of Things is on the shelf because of this, not because of food TV.",
    vibeLine: "Summer evening. One glass, one episode, no rush.",
  }),
  work({
    id: "servant",
    name: "Servant",
    year: "2019",
    kind: "series",
    runtime: "one episode",
    loved: true,
    fromChat: true,
    family: "domestic",
    vibes: ["folk", "dusk"],
    seasons: ["autumn", "winter"],
    facets: { domestic: 0.95, folk: 0.55, grief: 0.8, faith: 0.55, weird: 0.6 },
    summary:
      "A Philadelphia couple hires a nanny for a baby that is not what the house pretends. You finished it. Cult, grief, and the apartment.",
    why: "From the earlier chat, not this paste. Domestic uncanny — parenthood, faith-adjacent, rooms that won't open. Drop it on Taste if it shouldn't anchor.",
    vibeLine: "Closed rooms. One half-hour if the night is already strange.",
  }),
  work({
    id: "widows-bay",
    name: "Widow's Bay",
    year: "2026",
    kind: "series",
    runtime: "one episode",
    loved: true,
    fromChat: true,
    family: "folk",
    vibes: ["folk", "rewatch"],
    seasons: ["autumn", "summer"],
    facets: { folk: 0.75, weird: 0.6, satire: 0.55, domestic: 0.4, grief: 0.35, comfort: 0.35 },
    summary:
      "Matthew Rhys is the mayor of a cursed New England island. Horror and comedy in the same breath. You preferred it to From.",
    why: "From the earlier chat. Folk dread that is allowed to be funny, which is why it outranks From. Not preachy. Not a puzzle for its own sake.",
    vibeLine: "Island night. A scare and a joke, neither apologizing.",
  }),
];
