import { work, type Work } from "@/lib/work";

export const SHELF: Work[] = [
  work({
    id: "godfather",
    name: "The Godfather",
    year: "1972",
    runtime: "2h 55m",
    family: "crime",
    vibes: ["heat", "dusk"],
    seasons: ["autumn"],
    facets: { crime: 0.9, moral: 0.75, domestic: 0.7, talk: 0.55, faith: 0.25, cool: 0.4 },
    summary:
      "A war hero comes home for his sister's wedding and ends up heir to the family. The business is olive oil until it isn't.",
    why: "You built Goodfellas, Casino, Sopranos, A Bronx Tale, Once Upon a Time in America — and left the Corleones off the list. Dynastic, quieter, heavier at the table.",
    vibeLine: "Heat that behaves. A long night, family first.",
  }),
  work({
    id: "heat",
    name: "Heat",
    year: "1995",
    runtime: "2h 50m",
    family: "crime",
    vibes: ["heat", "dusk"],
    facets: { crime: 0.85, cool: 0.8, moral: 0.45, domestic: 0.4, talk: 0.4 },
    summary: "A thief and a detective in Los Angeles recognize each other. There is a coffee, and later a street.",
    why: "Goodfellas is appetite and friends. Heat is the same city as craft: professionals, a cold marriage, Bullitt's precision instead of a party.",
    vibeLine: "Night city. Professional, not glamorous.",
  }),
  work({
    id: "millers-crossing",
    name: "Miller's Crossing",
    year: "1990",
    runtime: "1h 55m",
    family: "crime",
    vibes: ["heat", "court"],
    facets: { crime: 0.8, talk: 0.75, moral: 0.55, cool: 0.6, satire: 0.25 },
    summary: "A political boss's right hand tries to keep a gang war from eating the town, and from eating him.",
    why: "Coen crime with manners. The Age of Innocence's cruelty, plus a hat in the woods. Talkier than Goodfellas, meaner than Ocean's.",
    vibeLine: "Heat in a overcoat. Loyalty as a tactic.",
  }),
  work({
    id: "a-prophet",
    name: "A Prophet",
    year: "2009",
    runtime: "2h 35m",
    family: "crime",
    vibes: ["heat"],
    facets: { crime: 0.85, moral: 0.6, institution: 0.55, obsession: 0.4, faith: 0.2 },
    summary: "A young Arab man enters a French prison illiterate and leaves it as someone the Corsicans did not plan.",
    why: "Education inside a crew. Breaking Bad's rise, without the American myth. Hard, long, and fair about what power costs the face.",
    vibeLine: "A serious heat night. Not a comfort crime film.",
  }),
  work({
    id: "irishman",
    name: "The Irishman",
    year: "2019",
    runtime: "3h 29m",
    family: "crime",
    vibes: ["heat", "dusk"],
    facets: { crime: 0.8, grief: 0.65, moral: 0.7, talk: 0.5 },
    summary: "An old hitman remembers the man he loved and the union man he was told to remove. Scorsese at the end of the party.",
    why: "You have the young Scorsese crime films. This is the hangover: Goodfellas' narrator if he had to sit with it. Only if you have the length of Once Upon a Time in America.",
    vibeLine: "The long one. Regret, not the Copacabana.",
  }),
  work({
    id: "donnie-brasco",
    name: "Donnie Brasco",
    year: "1997",
    runtime: "2h 7m",
    family: "crime",
    vibes: ["heat", "dusk"],
    facets: { crime: 0.8, moral: 0.65, spy: 0.45, domestic: 0.4, talk: 0.5 },
    summary: "An FBI agent becomes the friend of a small-time wise guy who vouches for him. The friendship is the crime.",
    why: "The Departed's double life, played as melancholy instead of a thriller. Sopranos' small soldiers, seen from the one who isn't really one.",
    vibeLine: "Heat, subdued. A friendship with a wire.",
  }),
  work({
    id: "gomorrah",
    name: "Gomorrah",
    year: "2014",
    kind: "series",
    runtime: "one episode",
    family: "crime",
    vibes: ["heat"],
    facets: { crime: 0.85, institution: 0.6, moral: 0.65, euro: 0.3 },
    summary: "Naples' Camorra as a system: housing projects, haute couture, teenagers with guns. Not a family you root for.",
    why: "The Wire's method, in Italian crime. If Goodfellas still feels too much like a good time, this is the correction.",
    vibeLine: "Heat without charm. One episode is enough to know.",
  }),
  work({
    id: "the-bureau",
    name: "The Bureau",
    year: "2015",
    kind: "series",
    runtime: "one episode",
    family: "spy",
    vibes: ["dusk"],
    seasons: ["autumn"],
    facets: { spy: 0.95, moral: 0.7, domestic: 0.45, talk: 0.55, institution: 0.6 },
    summary: "French foreign intelligence. A handler comes home from Damascus and the lie he lived there follows him into the office.",
    why: "The Americans if the institution were the point as much as the marriage. Tradecraft, guilt, no gadgets. The highest spy suggestion on the shelf.",
    vibeLine: "October, fluorescent. One episode of careful talk.",
  }),
  work({
    id: "tinker-tailor",
    name: "Tinker Tailor Soldier Spy",
    year: "2011",
    runtime: "2h 7m",
    family: "spy",
    vibes: ["dusk"],
    seasons: ["autumn", "winter"],
    facets: { spy: 0.95, moral: 0.6, institution: 0.7, talk: 0.55, cool: 0.35, grief: 0.3 },
    summary: "A retired spy is asked who in the Circus is Moscow's man. Rooms, files, and men who have already disappointed themselves.",
    why: "Skyfall is the autumn Bond with a house. This is the autumn spy film with no house left. The Americans' bureaucracy, British and exhausted.",
    vibeLine: "Dusk in an office. Patience required, and rewarded.",
  }),
  work({
    id: "lives-of-others",
    name: "The Lives of Others",
    year: "2006",
    runtime: "2h 17m",
    family: "spy",
    vibes: ["dusk", "court"],
    seasons: ["autumn"],
    facets: { spy: 0.75, moral: 0.85, institution: 0.7, talk: 0.5, grief: 0.4 },
    summary: "A Stasi officer wiretaps a playwright and starts to want the life he is destroying. East Berlin, 1984.",
    why: "Surveillance as a moral education. The Americans from the other side of the wall — one listener, not a marriage.",
    vibeLine: "Grey dusk. Headphones, a typewriter, a choice.",
  }),
  work({
    id: "deutschland-83",
    name: "Deutschland 83",
    year: "2015",
    kind: "series",
    runtime: "one episode",
    family: "spy",
    vibes: ["dusk", "summer"],
    facets: { spy: 0.8, moral: 0.55, cool: 0.35, euro: 0.4, satire: 0.25 },
    summary: "A young East German officer is thrown into the West as an aide. Pop songs, a possible war, a man not ready for either.",
    why: "The Americans, earlier and lonelier. Period craft, a moral education he didn't request. Shorter than a mythology.",
    vibeLine: "Night drive on the autobahn. One episode, then see.",
  }),
  work({
    id: "munich",
    name: "Munich",
    year: "2005",
    runtime: "2h 44m",
    family: "spy",
    vibes: ["dusk"],
    facets: { spy: 0.7, moral: 0.9, war: 0.45, grief: 0.5, talk: 0.4 },
    summary: "After the Olympic murders, a team is sent to kill the men Israel holds responsible. The list does not stay clean.",
    why: "Spy work as conscience. No Time to Die's grief without the tuxedo. You can take a film that argues with its own mission.",
    vibeLine: "Heavy dusk. Not a revenge fantasy.",
  }),
  work({
    id: "army-of-shadows",
    name: "Army of Shadows",
    year: "1969",
    runtime: "2h 25m",
    family: "war",
    vibes: ["dusk"],
    facets: { war: 0.7, spy: 0.65, moral: 0.85, grief: 0.55 },
    summary: "The French Resistance as logistics and betrayal. Brave, and often ugly about what the cell must do to itself.",
    why: "The Americans' moral bill, in occupied France. Band of Brothers believes in the unit. This one counts the cost of staying loyal.",
    vibeLine: "Grey, adult, no triumph score.",
  }),
  work({
    id: "ronin",
    name: "Ronin",
    year: "1998",
    runtime: "2h 2m",
    family: "spy",
    vibes: ["heat", "summer"],
    seasons: ["summer"],
    facets: { spy: 0.55, cool: 0.75, crime: 0.5, euro: 0.35 },
    summary: "Mercenaries in France chase a case nobody will explain. The car chases are the character work.",
    why: "Bullitt's attention, Casino Royale's Europe, none of the quips. A craft night when you want bodies in motion and thin talk.",
    vibeLine: "Summer asphalt. Chase, then a quiet double-cross.",
  }),
  work({
    id: "the-leftovers",
    name: "The Leftovers",
    year: "2014",
    kind: "series",
    runtime: "one episode",
    family: "grief",
    vibes: ["folk", "dusk"],
    seasons: ["autumn"],
    facets: { grief: 0.9, faith: 0.7, weird: 0.65, domestic: 0.6, moral: 0.55 },
    summary: "Two percent of the world vanishes. A town tries cults, police work, and family to explain a thing that will not explain.",
    why: "The strongest unseen match. Hamnet's grief, Twin Peaks' refusal to solve, Leviathan's faith without a sermon. Not a puzzle box.",
    vibeLine: "October. Start at season one. It becomes stranger, on purpose.",
  }),
  work({
    id: "the-returned",
    name: "The Returned",
    year: "2012",
    kind: "series",
    runtime: "one episode",
    family: "folk",
    vibes: ["folk", "dusk"],
    seasons: ["autumn", "winter"],
    facets: { folk: 0.7, grief: 0.85, weird: 0.6, domestic: 0.65, faith: 0.25 },
    summary: "The dead of a French town walk back in, the age they were, and sit down to dinner. The living are not ready.",
    why: "Servant's domestic impossible, Lamb's quiet, a whole town. Prefer this to another maze like From — the feeling is the plot.",
    vibeLine: "Damp night. The French series, not the remake.",
  }),
  work({
    id: "devs",
    name: "Devs",
    year: "2020",
    kind: "series",
    runtime: "one episode",
    family: "institution",
    vibes: ["dusk"],
    facets: { institution: 0.8, weird: 0.6, moral: 0.55, faith: 0.35, grief: 0.4, cool: 0.3 },
    summary: "A coder at a quantum company looks for her boyfriend inside a project that might already know the future.",
    why: "Severance's campus, Arrival's determinism, Garland's cold tone — you already trusted him with Warfare. Short series.",
    vibeLine: "Glass and redwoods. One episode, then the idea has you.",
  }),
  work({
    id: "counterpart",
    name: "Counterpart",
    year: "2017",
    kind: "series",
    runtime: "one episode",
    family: "institution",
    vibes: ["dusk"],
    facets: { institution: 0.75, spy: 0.7, weird: 0.45, moral: 0.55, domestic: 0.4 },
    summary: "A quiet UN clerk in Berlin learns there is another him across a door, and the other one is better at the life.",
    why: "Fringe's double world, played as The Americans: offices, marriages, spies. Identity without a speech about identity.",
    vibeLine: "Berlin dusk. Two men, one name.",
  }),
  work({
    id: "dark",
    name: "Dark",
    year: "2017",
    kind: "series",
    runtime: "one episode",
    family: "weird",
    vibes: ["folk", "dusk"],
    seasons: ["autumn"],
    facets: { weird: 0.85, grief: 0.55, folk: 0.4, domestic: 0.5, faith: 0.2 },
    summary: "Children go missing in a German town that is stuck in its own family tree. Time is not a metaphor.",
    why: "Fringe and Donnie Darko if they had stayed with one town. A diagram, yes — only start it if you want the diagram, unlike a Lamb night.",
    vibeLine: "Woods, bunkers, a chart you will pause.",
  }),
  work({
    id: "andor",
    name: "Andor",
    year: "2022",
    kind: "series",
    runtime: "one episode",
    family: "institution",
    vibes: ["dusk", "court"],
    facets: { institution: 0.8, moral: 0.75, spy: 0.55, war: 0.45, talk: 0.5 },
    summary: "A thief becomes useful to a rebellion that is mostly meetings, prisons, and people who will be spent.",
    why: "You like crafted sagas — LOTR, Bond, Nolan — when the institution has a moral cost. This is the one in that universe that behaves like The Bureau.",
    vibeLine: "Dusk politics. Skip if you wanted space noise.",
  }),
  work({
    id: "silence",
    name: "Silence",
    year: "2016",
    runtime: "2h 41m",
    family: "faith",
    vibes: ["folk", "court"],
    seasons: ["winter"],
    facets: { faith: 0.95, moral: 0.8, grief: 0.6, folk: 0.35, war: 0.25 },
    summary: "Two Jesuit priests go to Japan to find a mentor who may have renounced God. The film waits with them.",
    why: "Scorsese, whom you already trust, on faith as endurance rather than triumph. Passion is the body. This is the silence after. Not a sermon.",
    vibeLine: "Winter. Mud, a choice, no comfort music.",
  }),
  work({
    id: "first-reformed",
    name: "First Reformed",
    year: "2017",
    runtime: "1h 53m",
    family: "faith",
    vibes: ["dusk", "folk"],
    facets: { faith: 0.85, moral: 0.8, grief: 0.55, obsession: 0.5, talk: 0.45 },
    summary: "A small-church pastor keeps a journal, meets a radical, and starts to come apart in the rectory.",
    why: "Faith in crisis, Paul Schrader, austere as Leviathan. It does not tell you to agree with him. Whiplash's single-mindedness, pointed at God.",
    vibeLine: "A bare room. Only if you want the argument.",
  }),
  work({
    id: "loveless",
    name: "Loveless",
    year: "2017",
    runtime: "2h 7m",
    family: "grief",
    vibes: ["dusk"],
    seasons: ["winter"],
    facets: { grief: 0.85, moral: 0.7, domestic: 0.75, faith: 0.15 },
    summary: "A divorcing Moscow couple notice, late, that their son is gone. Zvyagintsev again, after Leviathan.",
    why: "You already live with Leviathan. This is the domestic one: a missing child as the verdict on a household. Manchester's refusal, Russian.",
    vibeLine: "Winter city. Cold on purpose.",
  }),
  work({
    id: "return-2003",
    name: "The Return",
    year: "2003",
    runtime: "1h 50m",
    family: "grief",
    vibes: ["folk", "dusk"],
    seasons: ["summer", "autumn"],
    facets: { grief: 0.75, folk: 0.4, moral: 0.65, domestic: 0.55 },
    summary: "Zvyagintsev. Two boys are taken on a trip by a father they do not remember. An island, a knife, a test.",
    why: "Not Twin Peaks. The other Return: fathers, silence, a landscape that judges. The Hunt and Lamb understand this quiet.",
    vibeLine: "Water and a father. Short, hard, plain.",
  }),
  work({
    id: "a-separation",
    name: "A Separation",
    year: "2011",
    runtime: "2h 3m",
    family: "grief",
    vibes: ["dusk", "court"],
    facets: { moral: 0.9, domestic: 0.8, talk: 0.75, faith: 0.35, grief: 0.45 },
    summary: "A Tehran marriage comes apart, and a fight with a caretaker becomes a court case nobody can tell honestly.",
    why: "Moral weight in a household, the way The Hunt and Defending Jacob work: everyone has a reason, and the reason is not enough.",
    vibeLine: "Talk in a kitchen, then a courtroom. No villains.",
  }),
  work({
    id: "aftersun",
    name: "Aftersun",
    year: "2022",
    runtime: "1h 42m",
    family: "grief",
    vibes: ["summer", "dusk"],
    seasons: ["summer"],
    facets: { grief: 0.85, domestic: 0.55, euro: 0.45, moral: 0.3 },
    summary: "A father and daughter on a cheap Turkish holiday, remembered later by the daughter who finally understands the trip.",
    why: "Parenthood without horror furniture. Hamnet and Manchester, whispered. Euro light used for sadness, not for Vicky Cristina's mess.",
    vibeLine: "Late summer. Small, and it stays.",
  }),
  work({
    id: "festen",
    name: "Festen",
    year: "1998",
    runtime: "1h 45m",
    family: "domestic",
    vibes: ["heat", "court"],
    facets: { domestic: 0.85, moral: 0.8, satire: 0.35, talk: 0.6, grief: 0.55 },
    summary: "A Danish birthday. The eldest son stands up and says what the family did. Nobody wants dessert interrupted.",
    why: "The Hunt's country, a family instead of a town. Manners as violence — Age of Innocence with the gloves off.",
    vibeLine: "A dinner you cannot leave. Danish, handheld, short.",
  }),
  work({
    id: "babadook",
    name: "The Babadook",
    year: "2014",
    runtime: "1h 34m",
    family: "domestic",
    vibes: ["folk", "dusk"],
    facets: { domestic: 0.8, grief: 0.85, folk: 0.55, weird: 0.4 },
    summary: "A widow and her son read a pop-up book that will not leave the house. The monster is grief with a hat.",
    why: "Lamb's parenthood, Servant's house, louder. Not a sermon about loss — the loss is allowed to be monstrous.",
    vibeLine: "One sitting. House, child, no joke except the book.",
  }),
  work({
    id: "saint-maud",
    name: "Saint Maud",
    year: "2019",
    runtime: "1h 24m",
    family: "faith",
    vibes: ["folk"],
    seasons: ["autumn"],
    facets: { faith: 0.85, obsession: 0.7, folk: 0.4, grief: 0.45, domestic: 0.35 },
    summary: "A private nurse believes God wants a special suffering from her and from the dying dancer she cares for.",
    why: "Faith as obsession, which you already keep in Passion and Whiplash. Austere, short, not a tract. It is afraid of her certainty.",
    vibeLine: "Coastal town, one woman, a private god.",
  }),
  work({
    id: "let-the-right-one-in",
    name: "Let the Right One In",
    year: "2008",
    runtime: "1h 54m",
    family: "folk",
    vibes: ["folk"],
    seasons: ["winter"],
    facets: { folk: 0.7, grief: 0.55, domestic: 0.4, moral: 0.45, weird: 0.5 },
    summary: "A bullied boy in a Swedish suburb meets a child who is not a child. Snow, and a friendship with rules.",
    why: "Horror as a lonely contract. It Follows' rules, Lamb's tenderness, none of the American gloss. The Swedish one, not the remake.",
    vibeLine: "Winter dark at 3pm. Quiet on purpose.",
  }),
  work({
    id: "the-orphanage",
    name: "The Orphanage",
    year: "2007",
    runtime: "1h 45m",
    family: "domestic",
    vibes: ["folk"],
    seasons: ["autumn"],
    facets: { domestic: 0.7, grief: 0.8, folk: 0.6, faith: 0.2, weird: 0.35 },
    summary: "A woman returns to the orphanage where she grew up, and her son starts to play with children who are not there.",
    why: "Servant and Hereditary's lost child, Spanish, and more tender than either. A ghost story that is actually about a mother.",
    vibeLine: "An old house. Sad more than cruel.",
  }),
  work({
    id: "innocents-2021",
    name: "The Innocents",
    year: "2021",
    runtime: "1h 57m",
    family: "folk",
    vibes: ["folk", "summer"],
    seasons: ["summer"],
    facets: { folk: 0.55, moral: 0.6, domestic: 0.45, weird: 0.5, grief: 0.3 },
    summary: "Norwegian children on a housing estate discover what they can do to each other when the adults are inside. Summer light, bad games.",
    why: "The Hunt's question — what children are capable of knowing — without the courtroom. Not cute magic. A bright, uneasy day.",
    vibeLine: "Summer that goes wrong. Quiet apartment blocks.",
  }),
  work({
    id: "his-house",
    name: "His House",
    year: "2020",
    runtime: "1h 33m",
    family: "folk",
    vibes: ["folk", "dusk"],
    facets: { folk: 0.7, grief: 0.75, domestic: 0.65, moral: 0.6, faith: 0.25 },
    summary: "A refugee couple in an English house are haunted by what they did to get on the boat. The walls know.",
    why: "Folk horror as guilt and parenthood. Lamb's quiet bargain, moved into a council house. It does not lecture you about borders.",
    vibeLine: "Short. A house that should have been safety.",
  }),
  work({
    id: "lighthouse",
    name: "The Lighthouse",
    year: "2019",
    runtime: "1h 49m",
    family: "weird",
    vibes: ["folk"],
    seasons: ["winter"],
    facets: { weird: 0.75, folk: 0.55, obsession: 0.5, faith: 0.3, satire: 0.25 },
    summary: "Two wickies on a rock lose the difference between work, drink, and myth. Black and white, and loud.",
    why: "The Witch's director, funnier and drunker. Folk without a family — obsession and weather. A stretch from Lamb toward Raging Bull's body.",
    vibeLine: "Storm night. Not subtle. Not long.",
  }),
  work({
    id: "november",
    name: "November",
    year: "2017",
    runtime: "1h 55m",
    family: "folk",
    vibes: ["folk"],
    seasons: ["autumn", "winter"],
    facets: { folk: 0.95, faith: 0.45, weird: 0.6, euro: 0.2, grief: 0.3 },
    summary: "Estonian peasants bargain with the devil, build servants out of farm tools, and still manage to fall in love badly.",
    why: "You Won't Be Alone's village magic, stranger and drier. If Lamb felt too restrained, this is the pagan one. Not a jump film.",
    vibeLine: "Black and white village. The title is the season.",
  }),
  work({
    id: "you-are-not-my-mother",
    name: "You Are Not My Mother",
    year: "2021",
    runtime: "1h 33m",
    family: "folk",
    vibes: ["folk"],
    seasons: ["autumn"],
    facets: { folk: 0.75, domestic: 0.7, grief: 0.55, faith: 0.25 },
    summary: "A Dublin teenager's mother disappears and comes back wrong, just as the neighborhood prepares a folk fire.",
    why: "Servant's replaced person, Irish, smaller than Hereditary. Family horror that still cares about the girl at school.",
    vibeLine: "Halloween streets. A short, sad one.",
  }),
  work({
    id: "wolf-hall",
    name: "Wolf Hall",
    year: "2015",
    kind: "series",
    runtime: "one episode",
    family: "court",
    vibes: ["court", "dusk"],
    facets: { court: 0.9, talk: 0.7, moral: 0.65, faith: 0.4, spy: 0.35 },
    summary: "Thomas Cromwell, low-born, keeps Henry VIII's will from breaking the state. Candlelight, and very little shouting.",
    why: "You wrote Thomas Cromwell under Steve McQueen. This is the Cromwell: court as a crime family, a still face, patience. Tudors is the soap. This is the knife under it.",
    vibeLine: "Court at dusk. Speak softly. The first series.",
  }),
  work({
    id: "barry-lyndon",
    name: "Barry Lyndon",
    year: "1975",
    runtime: "3h 5m",
    family: "court",
    vibes: ["court", "summer"],
    facets: { court: 0.85, moral: 0.55, cool: 0.5, war: 0.3, satire: 0.35, euro: 0.4 },
    summary: "An Irish nobody climbs into the aristocracy by duel, marriage, and luck, and the narration already pities him.",
    why: "The Age of Innocence's cruel manners, painted. A long euro-court night. Kubrick, so the beauty is a trap, not a postcard.",
    vibeLine: "Only with three hours. Candlelight, a rise, a fall.",
  }),
  work({
    id: "shogun",
    name: "Shōgun",
    year: "2024",
    kind: "series",
    runtime: "one episode",
    family: "court",
    vibes: ["court", "dusk"],
    facets: { court: 0.85, spy: 0.45, war: 0.5, moral: 0.55, faith: 0.3, talk: 0.4 },
    summary: "An English pilot is wrecked in Japan and becomes useful to a lord who is not supposed to win. Translation is power.",
    why: "Court, war, and a stranger who doesn't know the rules — Medici's intrigue with The Americans' double understanding. Limited series.",
    vibeLine: "Rain on wood. One episode to see if the patience fits.",
  }),
  work({
    id: "rome",
    name: "Rome",
    year: "2005",
    kind: "series",
    runtime: "one episode",
    family: "court",
    vibes: ["court", "heat"],
    facets: { court: 0.8, crime: 0.45, war: 0.5, moral: 0.4, faith: 0.25 },
    summary: "The end of the Republic, told through two soldiers and the families who use them. Dirt under the marble.",
    why: "Tudors' appetite with Band of Brothers' rank and file. Historical power as a street, which is also Gangs of New York.",
    vibeLine: "Court with mud. An episode, not a lecture.",
  }),
  work({
    id: "thin-red-line",
    name: "The Thin Red Line",
    year: "1998",
    runtime: "2h 50m",
    family: "war",
    vibes: ["dusk", "folk"],
    facets: { war: 0.85, faith: 0.4, grief: 0.55, moral: 0.6, folk: 0.25 },
    summary: "Guadalcanal, whispered. Men in tall grass ask what a soul is doing in a battle. Malick, so the island answers back.",
    why: "Dunkirk is a clock. This is the war film that behaves like folk: awe, cruelty, no briefing. A stretch, and a real one.",
    vibeLine: "Long, green, quiet between the assaults.",
  }),
  work({
    id: "come-and-see",
    name: "Come and See",
    year: "1985",
    runtime: "2h 22m",
    family: "war",
    vibes: ["folk"],
    facets: { war: 0.95, grief: 0.8, folk: 0.35, faith: 0.2, moral: 0.55 },
    summary: "A Belarusian boy joins the partisans and the war removes his face. The harshest thing on this shelf. Not a tonight if you wanted Bond.",
    why: "Only because Warfare and Dunkirk are clean by comparison, and Leviathan proved you can sit with Russian dread. All-time weight, low tonight unless you mean it.",
    vibeLine: "Do not put this on casually. Once is the point.",
  }),
  work({
    id: "chernobyl",
    name: "Chernobyl",
    year: "2019",
    kind: "series",
    runtime: "one episode",
    family: "institution",
    vibes: ["dusk"],
    facets: { institution: 0.85, moral: 0.8, war: 0.25, grief: 0.45, talk: 0.5 },
    summary: "The reactor burns and the state decides what may be said about it. Scientists, miners, and a lie with a deadline.",
    why: "The Wire's system failure, Soviet, five episodes. Leviathan's state, with a physical emergency. Limited, so it can be a week rather than a life.",
    vibeLine: "Dusk, procedural. Start at the beginning. It's short.",
  }),
  work({
    id: "all-quiet",
    name: "All Quiet on the Western Front",
    year: "2022",
    runtime: "2h 28m",
    family: "war",
    vibes: ["dusk"],
    seasons: ["autumn"],
    facets: { war: 0.9, grief: 0.6, moral: 0.5 },
    summary: "German boys are sent to the trenches and the mud keeps the uniform longer than the person. The recent one.",
    why: "Dunkirk's craft from the other trench, less triumphant on purpose. A war night when Band of Brothers feels too much like legend.",
    vibeLine: "Mud and a ceasefire that lies. One sitting.",
  }),
  work({
    id: "oppenheimer",
    name: "Oppenheimer",
    year: "2023",
    runtime: "3h",
    family: "obsession",
    vibes: ["dusk", "court"],
    facets: { obsession: 0.8, moral: 0.85, institution: 0.6, talk: 0.7, war: 0.45 },
    summary: "The man who built the bomb, then the hearing that tries to unbuild the man. Nolan, mostly in rooms.",
    why: "You have Prestige, Inception, Interstellar, Dunkirk, Batman — not this. Less spectacle than Interstellar, more guilt. A hearing as a thriller.",
    vibeLine: "A long dusk. Talk, then the light.",
  }),
  work({
    id: "civil-war",
    name: "Civil War",
    year: "2024",
    runtime: "1h 49m",
    family: "war",
    vibes: ["heat"],
    facets: { war: 0.8, moral: 0.45, cool: 0.3, obsession: 0.25 },
    summary: "Journalists drive toward a White House that is about to fall. Garland again, after the mode of Warfare: look, don't explain.",
    why: "You already took Warfare. This is the sister film — a road, photographs, violence without a speech telling you the lesson.",
    vibeLine: "Tense, short, contemporary. Not a comfort.",
  }),
  work({
    id: "in-the-loop",
    name: "In the Loop",
    year: "2009",
    runtime: "1h 46m",
    family: "satire",
    vibes: ["heat", "court"],
    facets: { satire: 0.9, talk: 0.85, moral: 0.55, institution: 0.6, war: 0.25 },
    summary: "A British minister says the wrong thing about a war and the rooms on two continents try to use him. Swearing as policy.",
    why: "The Death of Stalin's director, aimed at a war that has not started. Satire with teeth, not a lecture about politics.",
    vibeLine: "Mean laughter. Committees, corridors, a coming war.",
  }),
  work({
    id: "force-majeure",
    name: "Force Majeure",
    year: "2014",
    runtime: "2h",
    family: "domestic",
    vibes: ["summer", "dusk"],
    seasons: ["winter"],
    facets: { domestic: 0.8, moral: 0.75, satire: 0.4, euro: 0.45, talk: 0.55 },
    summary: "An avalanche misses a ski resort family. The father ran. The holiday has to continue anyway.",
    why: "A marriage examined like The Hunt examines a town — one reflex, then days of talk. Euro setting, moral bruise, not a postcard.",
    vibeLine: "Snow and a restaurant. Uncomfortable on purpose.",
  }),
  work({
    id: "in-bruges",
    name: "In Bruges",
    year: "2008",
    runtime: "1h 47m",
    family: "crime",
    vibes: ["heat", "summer"],
    seasons: ["winter"],
    facets: { crime: 0.6, satire: 0.7, moral: 0.65, euro: 0.55, grief: 0.4, talk: 0.6 },
    summary: "Two hitmen are sent to hide in Bruges, which one of them hates on sight. Guilt is the job they can't finish.",
    why: "Crime comedy that still believes in damnation. Death of Stalin's laugh, Goodfellas' work, a European city used as purgatory.",
    vibeLine: "Night walk, a joke, then the point.",
  }),
  work({
    id: "la-piscine",
    name: "La Piscine",
    year: "1969",
    runtime: "2h 2m",
    family: "euro",
    vibes: ["summer"],
    seasons: ["summer"],
    facets: { euro: 0.95, moral: 0.45, talk: 0.4, crime: 0.3, cool: 0.35 },
    summary: "A couple at a villa near Saint-Tropez are joined by an old friend and his daughter. The pool does not stay innocent.",
    why: "Vicky Cristina Barcelona and The Talented Mr. Ripley, meaner and French. Desire that curdles. The euro-summer film your list implied and didn't name.",
    vibeLine: "Hot afternoon. Skin, a guest, a turn.",
  }),
  work({
    id: "taste-of-things",
    name: "The Taste of Things",
    year: "2023",
    runtime: "2h 15m",
    family: "euro",
    vibes: ["summer", "court"],
    seasons: ["summer", "autumn"],
    facets: { euro: 0.7, obsession: 0.55, grief: 0.4, talk: 0.35, comfort: 0.35 },
    summary: "A cook and the gourmet she works with in a 19th-century French kitchen. The love is in the sequence of dishes.",
    why: "Drops of God's attention — taste as a moral life — without a contest. Slow on purpose. A night you don't fill with a phone.",
    vibeLine: "Late summer kitchen. Sensual, not sweet.",
  }),
  work({
    id: "call-me",
    name: "Call Me by Your Name",
    year: "2017",
    runtime: "2h 12m",
    family: "euro",
    vibes: ["summer"],
    seasons: ["summer"],
    facets: { euro: 0.9, grief: 0.45, talk: 0.5, comfort: 0.3 },
    summary: "A teenage boy in 1980s Lombardy falls for the graduate student staying the summer. Peaches, a bike, an ending that waits.",
    why: "Euro summer in the Ripley landscape, tender instead of criminal. Only when the mood is heat and feeling, not a heist.",
    vibeLine: "Italian summer. Slow, then it hurts.",
  }),
  work({
    id: "mindhunter",
    name: "Mindhunter",
    year: "2017",
    kind: "series",
    runtime: "one episode",
    family: "crime",
    vibes: ["dusk"],
    facets: { crime: 0.7, institution: 0.65, talk: 0.7, moral: 0.55, obsession: 0.45 },
    summary: "FBI agents interview locked-up killers to build a language for the ones still outside. Two seasons, then it stops.",
    why: "Hannibal's subject, Fincher's dryness. Black Bird's cell talk as a method. You like the conversation more than the gore.",
    vibeLine: "Tape recorder dusk. One interview.",
  }),
  work({
    id: "zodiac",
    name: "Zodiac",
    year: "2007",
    runtime: "2h 37m",
    family: "obsession",
    vibes: ["dusk"],
    facets: { obsession: 0.85, crime: 0.65, institution: 0.4, talk: 0.5, moral: 0.35 },
    summary: "A cartoonist and a reporter chase the Zodiac killer until the chase replaces their lives. The case does not oblige them.",
    why: "Obsession without a win, which Whiplash refuses and this film allows. Procedural like The Killing, American newspapers instead of Danish rain.",
    vibeLine: "A long dusk. The point is not catching him.",
  }),
  work({
    id: "anatomy-of-a-fall",
    name: "Anatomy of a Fall",
    year: "2023",
    runtime: "2h 31m",
    family: "domestic",
    vibes: ["dusk", "court"],
    facets: { domestic: 0.75, moral: 0.8, talk: 0.85, institution: 0.45, grief: 0.4 },
    summary: "A man dies at a chalet. His wife is tried. Their blind son listens to a marriage become evidence.",
    why: "Presumed Innocent and A Separation share this: a household turned into a case. Talk is the action. No twist required.",
    vibeLine: "Snow, a court, a marriage played back on tape.",
  }),
  work({
    id: "prisoners",
    name: "Prisoners",
    year: "2013",
    runtime: "2h 33m",
    family: "grief",
    vibes: ["folk", "dusk"],
    seasons: ["autumn"],
    facets: { grief: 0.75, moral: 0.8, crime: 0.65, domestic: 0.55, faith: 0.35 },
    summary: "Two girls vanish on Thanksgiving. One father stops trusting the police. Rain, basements, a knot that may be religious.",
    why: "Defending Jacob's parental terror, darker, with a folk streak in the clues. Autumn on purpose. Not empty cruelty — it asks what you'll do.",
    vibeLine: "Thanksgiving rain. Grim, complete, one sitting.",
  }),
  work({
    id: "black-swan",
    name: "Black Swan",
    year: "2010",
    runtime: "1h 48m",
    family: "obsession",
    vibes: ["dusk"],
    facets: { obsession: 0.9, weird: 0.55, domestic: 0.35, grief: 0.3 },
    summary: "A dancer is cast as the swan who has to be both innocent and ruined. Her body starts keeping score.",
    why: "Whiplash in a tutu, stranger. Mastery as self-erasure. A stretch toward Hereditary's body horror if you want the obsession first.",
    vibeLine: "One tense night. Mirrors, a role, a mother.",
  }),
  work({
    id: "amadeus",
    name: "Amadeus",
    year: "1984",
    runtime: "2h 40m",
    family: "obsession",
    vibes: ["court", "rewatch"],
    facets: { obsession: 0.8, court: 0.65, satire: 0.35, faith: 0.3, talk: 0.45, moral: 0.4 },
    summary: "Salieri tells God why Mozart had to be punished for being better. Court, laughter, and a very small man.",
    why: "Whiplash's envy without the teacher-as-hero. Court spectacle you can trust because the joke is on mediocrity, including the narrator.",
    vibeLine: "A long, bright, cruel rewatch-to-be. Music loud.",
  }),
  work({
    id: "social-network",
    name: "The Social Network",
    year: "2010",
    runtime: "2h",
    family: "obsession",
    vibes: ["heat", "dusk"],
    facets: { obsession: 0.75, talk: 0.85, moral: 0.55, institution: 0.4, cool: 0.45 },
    summary: "A college slight becomes a company, and the friendships are in depositions. Sorkin talk, Fincher temperature.",
    why: "Marty Supreme's hustle in a deposition. Talk as combat, which is Mad Men and In the Loop. Ambition without a gangster excuse.",
    vibeLine: "Fast talk. A complete story in one night.",
  }),
  work({
    id: "the-bridge",
    name: "The Bridge",
    year: "2011",
    kind: "series",
    runtime: "one episode",
    family: "crime",
    vibes: ["dusk", "folk"],
    seasons: ["autumn", "winter"],
    facets: { crime: 0.7, moral: 0.6, institution: 0.45, euro: 0.25, talk: 0.4 },
    summary: "The Danish-Swedish one. A body on the Øresund bridge, two detectives who do not work the same way, a case that widens.",
    why: "You named the Danish Killing. This is the next weather: cross-border, colder jokes, the same patience with a case.",
    vibeLine: "Rain and a bridge. Season one. Stop there if you want.",
  }),
  work({
    id: "ripley-note",
    name: "Purple Noon",
    year: "1960",
    runtime: "1h 58m",
    family: "euro",
    vibes: ["summer"],
    seasons: ["summer"],
    facets: { euro: 0.9, crime: 0.55, cool: 0.6, moral: 0.35 },
    summary: "The French Ripley, Alain Delon in the sun, before the 1999 film and the 2024 series you already love. A boat, a friend, a theft of a life.",
    why: "You said both Ripleys. If those were the Minghella film and the Netflix series, this is the third, the one that is pure euro summer — cruel and beautiful.",
    vibeLine: "Mediterranean. The oldest Ripley, the brightest water.",
  }),
];
